from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class AccountApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def get_account(self, **kwargs): ...
    def get_account_with_http_info(self, **kwargs): ...
