from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class AttributesApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def create_attribute(self, attribute_category, attribute_name, create_attribute, **kwargs): ...
    def create_attribute_with_http_info(self, attribute_category, attribute_name, create_attribute, **kwargs): ...
    def delete_attribute(self, attribute_category, attribute_name, **kwargs): ...
    def delete_attribute_with_http_info(self, attribute_category, attribute_name, **kwargs): ...
    def get_attributes(self, **kwargs): ...
    def get_attributes_with_http_info(self, **kwargs): ...
    def update_attribute(self, attribute_category, attribute_name, update_attribute, **kwargs): ...
    def update_attribute_with_http_info(self, attribute_category, attribute_name, update_attribute, **kwargs): ...
