from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class CompaniesApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def companies_attributes_get(self, **kwargs): ...
    def companies_attributes_get_with_http_info(self, **kwargs): ...
    def companies_get(self, **kwargs): ...
    def companies_get_with_http_info(self, **kwargs): ...
    def companies_id_delete(self, id, **kwargs): ...
    def companies_id_delete_with_http_info(self, id, **kwargs): ...
    def companies_id_get(self, id, **kwargs): ...
    def companies_id_get_with_http_info(self, id, **kwargs): ...
    def companies_id_patch(self, id, body, **kwargs): ...
    def companies_id_patch_with_http_info(self, id, body, **kwargs): ...
    def companies_link_unlink_id_patch(self, id, body, **kwargs): ...
    def companies_link_unlink_id_patch_with_http_info(self, id, body, **kwargs): ...
    def companies_post(self, body, **kwargs): ...
    def companies_post_with_http_info(self, body, **kwargs): ...
