from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class ContactsApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def add_contact_to_list(self, list_id, contact_emails, **kwargs): ...
    def add_contact_to_list_with_http_info(self, list_id, contact_emails, **kwargs): ...
    def create_attribute(self, attribute_category, attribute_name, create_attribute, **kwargs): ...
    def create_attribute_with_http_info(self, attribute_category, attribute_name, create_attribute, **kwargs): ...
    def create_contact(self, create_contact, **kwargs): ...
    def create_contact_with_http_info(self, create_contact, **kwargs): ...
    def create_doi_contact(self, create_doi_contact, **kwargs): ...
    def create_doi_contact_with_http_info(self, create_doi_contact, **kwargs): ...
    def create_folder(self, create_folder, **kwargs): ...
    def create_folder_with_http_info(self, create_folder, **kwargs): ...
    def create_list(self, create_list, **kwargs): ...
    def create_list_with_http_info(self, create_list, **kwargs): ...
    def delete_attribute(self, attribute_category, attribute_name, **kwargs): ...
    def delete_attribute_with_http_info(self, attribute_category, attribute_name, **kwargs): ...
    def delete_contact(self, identifier, **kwargs): ...
    def delete_contact_with_http_info(self, identifier, **kwargs): ...
    def delete_folder(self, folder_id, **kwargs): ...
    def delete_folder_with_http_info(self, folder_id, **kwargs): ...
    def delete_list(self, list_id, **kwargs): ...
    def delete_list_with_http_info(self, list_id, **kwargs): ...
    def get_attributes(self, **kwargs): ...
    def get_attributes_with_http_info(self, **kwargs): ...
    def get_contact_info(self, identifier, **kwargs): ...
    def get_contact_info_with_http_info(self, identifier, **kwargs): ...
    def get_contact_stats(self, identifier, **kwargs): ...
    def get_contact_stats_with_http_info(self, identifier, **kwargs): ...
    def get_contacts(self, **kwargs): ...
    def get_contacts_with_http_info(self, **kwargs): ...
    def get_contacts_from_list(self, list_id, **kwargs): ...
    def get_contacts_from_list_with_http_info(self, list_id, **kwargs): ...
    def get_folder(self, folder_id, **kwargs): ...
    def get_folder_with_http_info(self, folder_id, **kwargs): ...
    def get_folder_lists(self, folder_id, **kwargs): ...
    def get_folder_lists_with_http_info(self, folder_id, **kwargs): ...
    def get_folders(self, limit, offset, **kwargs): ...
    def get_folders_with_http_info(self, limit, offset, **kwargs): ...
    def get_list(self, list_id, **kwargs): ...
    def get_list_with_http_info(self, list_id, **kwargs): ...
    def get_lists(self, **kwargs): ...
    def get_lists_with_http_info(self, **kwargs): ...
    def import_contacts(self, request_contact_import, **kwargs): ...
    def import_contacts_with_http_info(self, request_contact_import, **kwargs): ...
    def remove_contact_from_list(self, list_id, contact_emails, **kwargs): ...
    def remove_contact_from_list_with_http_info(self, list_id, contact_emails, **kwargs): ...
    def request_contact_export(self, request_contact_export, **kwargs): ...
    def request_contact_export_with_http_info(self, request_contact_export, **kwargs): ...
    def update_attribute(self, attribute_category, attribute_name, update_attribute, **kwargs): ...
    def update_attribute_with_http_info(self, attribute_category, attribute_name, update_attribute, **kwargs): ...
    def update_batch_contacts(self, update_batch_contacts, **kwargs): ...
    def update_batch_contacts_with_http_info(self, update_batch_contacts, **kwargs): ...
    def update_contact(self, identifier, update_contact, **kwargs): ...
    def update_contact_with_http_info(self, identifier, update_contact, **kwargs): ...
    def update_folder(self, folder_id, update_folder, **kwargs): ...
    def update_folder_with_http_info(self, folder_id, update_folder, **kwargs): ...
    def update_list(self, list_id, update_list, **kwargs): ...
    def update_list_with_http_info(self, list_id, update_list, **kwargs): ...
