from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class ConversationsApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def conversations_agent_online_ping_post(self, body, **kwargs): ...
    def conversations_agent_online_ping_post_with_http_info(self, body, **kwargs): ...
    def conversations_messages_id_delete(self, id, **kwargs): ...
    def conversations_messages_id_delete_with_http_info(self, id, **kwargs): ...
    def conversations_messages_id_get(self, id, **kwargs): ...
    def conversations_messages_id_get_with_http_info(self, id, **kwargs): ...
    def conversations_messages_id_put(self, id, **kwargs): ...
    def conversations_messages_id_put_with_http_info(self, id, **kwargs): ...
    def conversations_messages_post(self, body, **kwargs): ...
    def conversations_messages_post_with_http_info(self, body, **kwargs): ...
    def conversations_pushed_messages_id_delete(self, id, **kwargs): ...
    def conversations_pushed_messages_id_delete_with_http_info(self, id, **kwargs): ...
    def conversations_pushed_messages_id_get(self, id, **kwargs): ...
    def conversations_pushed_messages_id_get_with_http_info(self, id, **kwargs): ...
    def conversations_pushed_messages_id_put(self, id, body, **kwargs): ...
    def conversations_pushed_messages_id_put_with_http_info(self, id, body, **kwargs): ...
    def conversations_pushed_messages_post(self, body, **kwargs): ...
    def conversations_pushed_messages_post_with_http_info(self, body, **kwargs): ...
