from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class DealsApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def crm_attributes_deals_get(self, **kwargs): ...
    def crm_attributes_deals_get_with_http_info(self, **kwargs): ...
    def crm_deals_get(self, **kwargs): ...
    def crm_deals_get_with_http_info(self, **kwargs): ...
    def crm_deals_id_delete(self, id, **kwargs): ...
    def crm_deals_id_delete_with_http_info(self, id, **kwargs): ...
    def crm_deals_id_get(self, id, **kwargs): ...
    def crm_deals_id_get_with_http_info(self, id, **kwargs): ...
    def crm_deals_id_patch(self, id, body, **kwargs): ...
    def crm_deals_id_patch_with_http_info(self, id, body, **kwargs): ...
    def crm_deals_link_unlink_id_patch(self, id, body, **kwargs): ...
    def crm_deals_link_unlink_id_patch_with_http_info(self, id, body, **kwargs): ...
    def crm_deals_post(self, body, **kwargs): ...
    def crm_deals_post_with_http_info(self, body, **kwargs): ...
    def crm_pipeline_details_get(self, **kwargs): ...
    def crm_pipeline_details_get_with_http_info(self, **kwargs): ...
