from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class EcommerceApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def create_batch_order(self, order_batch, **kwargs): ...
    def create_batch_order_with_http_info(self, order_batch, **kwargs): ...
    def create_order(self, order, **kwargs): ...
    def create_order_with_http_info(self, order, **kwargs): ...
    def create_update_batch_category(self, create_update_batch_category, **kwargs): ...
    def create_update_batch_category_with_http_info(self, create_update_batch_category, **kwargs): ...
    def create_update_batch_products(self, create_update_batch_products, **kwargs): ...
    def create_update_batch_products_with_http_info(self, create_update_batch_products, **kwargs): ...
    def create_update_category(self, create_update_category, **kwargs): ...
    def create_update_category_with_http_info(self, create_update_category, **kwargs): ...
    def create_update_product(self, create_update_product, **kwargs): ...
    def create_update_product_with_http_info(self, create_update_product, **kwargs): ...
    def ecommerce_activate_post(self, **kwargs): ...
    def ecommerce_activate_post_with_http_info(self, **kwargs): ...
    def get_categories(self, **kwargs): ...
    def get_categories_with_http_info(self, **kwargs): ...
    def get_category_info(self, id, **kwargs): ...
    def get_category_info_with_http_info(self, id, **kwargs): ...
    def get_product_info(self, id, **kwargs): ...
    def get_product_info_with_http_info(self, id, **kwargs): ...
    def get_products(self, **kwargs): ...
    def get_products_with_http_info(self, **kwargs): ...
