from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class EmailCampaignsApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def create_email_campaign(self, email_campaigns, **kwargs): ...
    def create_email_campaign_with_http_info(self, email_campaigns, **kwargs): ...
    def delete_email_campaign(self, campaign_id, **kwargs): ...
    def delete_email_campaign_with_http_info(self, campaign_id, **kwargs): ...
    def email_export_recipients(self, campaign_id, **kwargs): ...
    def email_export_recipients_with_http_info(self, campaign_id, **kwargs): ...
    def get_ab_test_campaign_result(self, campaign_id, **kwargs): ...
    def get_ab_test_campaign_result_with_http_info(self, campaign_id, **kwargs): ...
    def get_email_campaign(self, campaign_id, **kwargs): ...
    def get_email_campaign_with_http_info(self, campaign_id, **kwargs): ...
    def get_email_campaigns(self, **kwargs): ...
    def get_email_campaigns_with_http_info(self, **kwargs): ...
    def get_shared_template_url(self, campaign_id, **kwargs): ...
    def get_shared_template_url_with_http_info(self, campaign_id, **kwargs): ...
    def send_email_campaign_now(self, campaign_id, **kwargs): ...
    def send_email_campaign_now_with_http_info(self, campaign_id, **kwargs): ...
    def send_report(self, campaign_id, send_report, **kwargs): ...
    def send_report_with_http_info(self, campaign_id, send_report, **kwargs): ...
    def send_test_email(self, campaign_id, email_to, **kwargs): ...
    def send_test_email_with_http_info(self, campaign_id, email_to, **kwargs): ...
    def update_campaign_status(self, campaign_id, status, **kwargs): ...
    def update_campaign_status_with_http_info(self, campaign_id, status, **kwargs): ...
    def update_email_campaign(self, campaign_id, email_campaign, **kwargs): ...
    def update_email_campaign_with_http_info(self, campaign_id, email_campaign, **kwargs): ...
    def upload_image_to_gallery(self, upload_image, **kwargs): ...
    def upload_image_to_gallery_with_http_info(self, upload_image, **kwargs): ...
