from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class ExternalFeedsApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def create_external_feed(self, create_external_feed, **kwargs): ...
    def create_external_feed_with_http_info(self, create_external_feed, **kwargs): ...
    def delete_external_feed(self, uuid, **kwargs): ...
    def delete_external_feed_with_http_info(self, uuid, **kwargs): ...
    def get_all_external_feeds(self, **kwargs): ...
    def get_all_external_feeds_with_http_info(self, **kwargs): ...
    def get_external_feed_by_uuid(self, uuid, **kwargs): ...
    def get_external_feed_by_uuid_with_http_info(self, uuid, **kwargs): ...
    def update_external_feed(self, uuid, update_external_feed, **kwargs): ...
    def update_external_feed_with_http_info(self, uuid, update_external_feed, **kwargs): ...
