from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class FilesApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def crm_files_get(self, **kwargs): ...
    def crm_files_get_with_http_info(self, **kwargs): ...
    def crm_files_id_data_get(self, id, **kwargs): ...
    def crm_files_id_data_get_with_http_info(self, id, **kwargs): ...
    def crm_files_id_delete(self, id, **kwargs): ...
    def crm_files_id_delete_with_http_info(self, id, **kwargs): ...
    def crm_files_id_get(self, id, **kwargs): ...
    def crm_files_id_get_with_http_info(self, id, **kwargs): ...
    def crm_files_post(self, file, **kwargs): ...
    def crm_files_post_with_http_info(self, file, **kwargs): ...
