from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class FoldersApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def create_folder(self, create_folder, **kwargs): ...
    def create_folder_with_http_info(self, create_folder, **kwargs): ...
    def delete_folder(self, folder_id, **kwargs): ...
    def delete_folder_with_http_info(self, folder_id, **kwargs): ...
    def get_folder(self, folder_id, **kwargs): ...
    def get_folder_with_http_info(self, folder_id, **kwargs): ...
    def get_folder_lists(self, folder_id, **kwargs): ...
    def get_folder_lists_with_http_info(self, folder_id, **kwargs): ...
    def get_folders(self, limit, offset, **kwargs): ...
    def get_folders_with_http_info(self, limit, offset, **kwargs): ...
    def update_folder(self, folder_id, update_folder, **kwargs): ...
    def update_folder_with_http_info(self, folder_id, update_folder, **kwargs): ...
