from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class InboundParsingApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def get_inbound_email_attachment(self, download_token, **kwargs): ...
    def get_inbound_email_attachment_with_http_info(self, download_token, **kwargs): ...
    def get_inbound_email_events(self, **kwargs): ...
    def get_inbound_email_events_with_http_info(self, **kwargs): ...
    def get_inbound_email_events_by_uuid(self, uuid, **kwargs): ...
    def get_inbound_email_events_by_uuid_with_http_info(self, uuid, **kwargs): ...
