from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class ListsApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def add_contact_to_list(self, list_id, contact_emails, **kwargs): ...
    def add_contact_to_list_with_http_info(self, list_id, contact_emails, **kwargs): ...
    def create_list(self, create_list, **kwargs): ...
    def create_list_with_http_info(self, create_list, **kwargs): ...
    def delete_list(self, list_id, **kwargs): ...
    def delete_list_with_http_info(self, list_id, **kwargs): ...
    def get_contacts_from_list(self, list_id, **kwargs): ...
    def get_contacts_from_list_with_http_info(self, list_id, **kwargs): ...
    def get_folder_lists(self, folder_id, **kwargs): ...
    def get_folder_lists_with_http_info(self, folder_id, **kwargs): ...
    def get_list(self, list_id, **kwargs): ...
    def get_list_with_http_info(self, list_id, **kwargs): ...
    def get_lists(self, **kwargs): ...
    def get_lists_with_http_info(self, **kwargs): ...
    def remove_contact_from_list(self, list_id, contact_emails, **kwargs): ...
    def remove_contact_from_list_with_http_info(self, list_id, contact_emails, **kwargs): ...
    def update_list(self, list_id, update_list, **kwargs): ...
    def update_list_with_http_info(self, list_id, update_list, **kwargs): ...
