from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class MasterAccountApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def corporate_master_account_get(self, **kwargs): ...
    def corporate_master_account_get_with_http_info(self, **kwargs): ...
    def corporate_sub_account_get(self, offset, limit, **kwargs): ...
    def corporate_sub_account_get_with_http_info(self, offset, limit, **kwargs): ...
    def corporate_sub_account_id_delete(self, id, **kwargs): ...
    def corporate_sub_account_id_delete_with_http_info(self, id, **kwargs): ...
    def corporate_sub_account_id_get(self, id, **kwargs): ...
    def corporate_sub_account_id_get_with_http_info(self, id, **kwargs): ...
    def corporate_sub_account_id_plan_put(self, id, update_plan_details, **kwargs): ...
    def corporate_sub_account_id_plan_put_with_http_info(self, id, update_plan_details, **kwargs): ...
    def corporate_sub_account_key_post(self, create_api_key_request, **kwargs): ...
    def corporate_sub_account_key_post_with_http_info(self, create_api_key_request, **kwargs): ...
    def corporate_sub_account_post(self, sub_account_create, **kwargs): ...
    def corporate_sub_account_post_with_http_info(self, sub_account_create, **kwargs): ...
    def corporate_sub_account_sso_token_post(self, sso_token_request, **kwargs): ...
    def corporate_sub_account_sso_token_post_with_http_info(self, sso_token_request, **kwargs): ...
