from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class ProcessApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def get_process(self, process_id, **kwargs): ...
    def get_process_with_http_info(self, process_id, **kwargs): ...
    def get_processes(self, **kwargs): ...
    def get_processes_with_http_info(self, **kwargs): ...
