from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class ResellerApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def add_credits(self, child_identifier, add_credits, **kwargs): ...
    def add_credits_with_http_info(self, child_identifier, add_credits, **kwargs): ...
    def associate_ip_to_child(self, child_identifier, ip, **kwargs): ...
    def associate_ip_to_child_with_http_info(self, child_identifier, ip, **kwargs): ...
    def create_child_domain(self, child_identifier, add_child_domain, **kwargs): ...
    def create_child_domain_with_http_info(self, child_identifier, add_child_domain, **kwargs): ...
    def create_reseller_child(self, **kwargs): ...
    def create_reseller_child_with_http_info(self, **kwargs): ...
    def delete_child_domain(self, child_identifier, domain_name, **kwargs): ...
    def delete_child_domain_with_http_info(self, child_identifier, domain_name, **kwargs): ...
    def delete_reseller_child(self, child_identifier, **kwargs): ...
    def delete_reseller_child_with_http_info(self, child_identifier, **kwargs): ...
    def dissociate_ip_from_child(self, child_identifier, ip, **kwargs): ...
    def dissociate_ip_from_child_with_http_info(self, child_identifier, ip, **kwargs): ...
    def get_child_account_creation_status(self, child_identifier, **kwargs): ...
    def get_child_account_creation_status_with_http_info(self, child_identifier, **kwargs): ...
    def get_child_domains(self, child_identifier, **kwargs): ...
    def get_child_domains_with_http_info(self, child_identifier, **kwargs): ...
    def get_child_info(self, child_identifier, **kwargs): ...
    def get_child_info_with_http_info(self, child_identifier, **kwargs): ...
    def get_reseller_childs(self, **kwargs): ...
    def get_reseller_childs_with_http_info(self, **kwargs): ...
    def get_sso_token(self, child_identifier, **kwargs): ...
    def get_sso_token_with_http_info(self, child_identifier, **kwargs): ...
    def remove_credits(self, child_identifier, remove_credits, **kwargs): ...
    def remove_credits_with_http_info(self, child_identifier, remove_credits, **kwargs): ...
    def update_child_account_status(self, child_identifier, update_child_account_status, **kwargs): ...
    def update_child_account_status_with_http_info(self, child_identifier, update_child_account_status, **kwargs): ...
    def update_child_domain(self, child_identifier, domain_name, update_child_domain, **kwargs): ...
    def update_child_domain_with_http_info(self, child_identifier, domain_name, update_child_domain, **kwargs): ...
    def update_reseller_child(self, child_identifier, reseller_child, **kwargs): ...
    def update_reseller_child_with_http_info(self, child_identifier, reseller_child, **kwargs): ...
