from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class SendersApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def create_sender(self, **kwargs): ...
    def create_sender_with_http_info(self, **kwargs): ...
    def delete_sender(self, sender_id, **kwargs): ...
    def delete_sender_with_http_info(self, sender_id, **kwargs): ...
    def get_ips(self, **kwargs): ...
    def get_ips_with_http_info(self, **kwargs): ...
    def get_ips_from_sender(self, sender_id, **kwargs): ...
    def get_ips_from_sender_with_http_info(self, sender_id, **kwargs): ...
    def get_senders(self, **kwargs): ...
    def get_senders_with_http_info(self, **kwargs): ...
    def update_sender(self, sender_id, **kwargs): ...
    def update_sender_with_http_info(self, sender_id, **kwargs): ...
