from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class SMSCampaignsApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def create_sms_campaign(self, create_sms_campaign, **kwargs): ...
    def create_sms_campaign_with_http_info(self, create_sms_campaign, **kwargs): ...
    def delete_sms_campaign(self, campaign_id, **kwargs): ...
    def delete_sms_campaign_with_http_info(self, campaign_id, **kwargs): ...
    def get_sms_campaign(self, campaign_id, **kwargs): ...
    def get_sms_campaign_with_http_info(self, campaign_id, **kwargs): ...
    def get_sms_campaigns(self, **kwargs): ...
    def get_sms_campaigns_with_http_info(self, **kwargs): ...
    def request_sms_recipient_export(self, campaign_id, **kwargs): ...
    def request_sms_recipient_export_with_http_info(self, campaign_id, **kwargs): ...
    def send_sms_campaign_now(self, campaign_id, **kwargs): ...
    def send_sms_campaign_now_with_http_info(self, campaign_id, **kwargs): ...
    def send_sms_report(self, campaign_id, send_report, **kwargs): ...
    def send_sms_report_with_http_info(self, campaign_id, send_report, **kwargs): ...
    def send_test_sms(self, campaign_id, phone_number, **kwargs): ...
    def send_test_sms_with_http_info(self, campaign_id, phone_number, **kwargs): ...
    def update_sms_campaign(self, campaign_id, update_sms_campaign, **kwargs): ...
    def update_sms_campaign_with_http_info(self, campaign_id, update_sms_campaign, **kwargs): ...
    def update_sms_campaign_status(self, campaign_id, status, **kwargs): ...
    def update_sms_campaign_status_with_http_info(self, campaign_id, status, **kwargs): ...
