from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class TransactionalSMSApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def get_sms_events(self, **kwargs): ...
    def get_sms_events_with_http_info(self, **kwargs): ...
    def get_transac_aggregated_sms_report(self, **kwargs): ...
    def get_transac_aggregated_sms_report_with_http_info(self, **kwargs): ...
    def get_transac_sms_report(self, **kwargs): ...
    def get_transac_sms_report_with_http_info(self, **kwargs): ...
    def send_transac_sms(self, send_transac_sms, **kwargs): ...
    def send_transac_sms_with_http_info(self, send_transac_sms, **kwargs): ...
