from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class TransactionalEmailsApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def block_new_domain(self, block_domain, **kwargs): ...
    def block_new_domain_with_http_info(self, block_domain, **kwargs): ...
    def create_smtp_template(self, smtp_template, **kwargs): ...
    def create_smtp_template_with_http_info(self, smtp_template, **kwargs): ...
    def delete_blocked_domain(self, domain, **kwargs): ...
    def delete_blocked_domain_with_http_info(self, domain, **kwargs): ...
    def delete_hardbounces(self, **kwargs): ...
    def delete_hardbounces_with_http_info(self, **kwargs): ...
    def delete_scheduled_email_by_id(self, identifier, **kwargs): ...
    def delete_scheduled_email_by_id_with_http_info(self, identifier, **kwargs): ...
    def delete_smtp_template(self, template_id, **kwargs): ...
    def delete_smtp_template_with_http_info(self, template_id, **kwargs): ...
    def get_aggregated_smtp_report(self, **kwargs): ...
    def get_aggregated_smtp_report_with_http_info(self, **kwargs): ...
    def get_blocked_domains(self, **kwargs): ...
    def get_blocked_domains_with_http_info(self, **kwargs): ...
    def get_email_event_report(self, **kwargs): ...
    def get_email_event_report_with_http_info(self, **kwargs): ...
    def get_scheduled_email_by_batch_id(self, batch_id, **kwargs): ...
    def get_scheduled_email_by_batch_id_with_http_info(self, batch_id, **kwargs): ...
    def get_scheduled_email_by_message_id(self, message_id, **kwargs): ...
    def get_scheduled_email_by_message_id_with_http_info(self, message_id, **kwargs): ...
    def get_smtp_report(self, **kwargs): ...
    def get_smtp_report_with_http_info(self, **kwargs): ...
    def get_smtp_template(self, template_id, **kwargs): ...
    def get_smtp_template_with_http_info(self, template_id, **kwargs): ...
    def get_smtp_templates(self, **kwargs): ...
    def get_smtp_templates_with_http_info(self, **kwargs): ...
    def get_transac_blocked_contacts(self, **kwargs): ...
    def get_transac_blocked_contacts_with_http_info(self, **kwargs): ...
    def get_transac_email_content(self, uuid, **kwargs): ...
    def get_transac_email_content_with_http_info(self, uuid, **kwargs): ...
    def get_transac_emails_list(self, **kwargs): ...
    def get_transac_emails_list_with_http_info(self, **kwargs): ...
    def send_test_template(self, template_id, send_test_email, **kwargs): ...
    def send_test_template_with_http_info(self, template_id, send_test_email, **kwargs): ...
    def send_transac_email(self, send_smtp_email, **kwargs): ...
    def send_transac_email_with_http_info(self, send_smtp_email, **kwargs): ...
    def smtp_blocked_contacts_email_delete(self, email, **kwargs): ...
    def smtp_blocked_contacts_email_delete_with_http_info(self, email, **kwargs): ...
    def smtp_log_message_id_delete(self, message_id, **kwargs): ...
    def smtp_log_message_id_delete_with_http_info(self, message_id, **kwargs): ...
    def update_smtp_template(self, template_id, smtp_template, **kwargs): ...
    def update_smtp_template_with_http_info(self, template_id, smtp_template, **kwargs): ...
