from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class TransactionalWhatsAppApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def get_whatsapp_event_report(self, **kwargs): ...
    def get_whatsapp_event_report_with_http_info(self, **kwargs): ...
    def send_whatsapp_message(self, send_whatsapp_message, **kwargs): ...
    def send_whatsapp_message_with_http_info(self, send_whatsapp_message, **kwargs): ...
