from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class WebhooksApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def create_webhook(self, create_webhook, **kwargs): ...
    def create_webhook_with_http_info(self, create_webhook, **kwargs): ...
    def delete_webhook(self, webhook_id, **kwargs): ...
    def delete_webhook_with_http_info(self, webhook_id, **kwargs): ...
    def get_webhook(self, webhook_id, **kwargs): ...
    def get_webhook_with_http_info(self, webhook_id, **kwargs): ...
    def get_webhooks(self, **kwargs): ...
    def get_webhooks_with_http_info(self, **kwargs): ...
    def update_webhook(self, webhook_id, update_webhook, **kwargs): ...
    def update_webhook_with_http_info(self, webhook_id, update_webhook, **kwargs): ...
