from _typeshed import Incomplete
from sib_api_v3_sdk.api_client import ApiClient as ApiClient

class WhatsappCampaignsApi:
    api_client: Incomplete
    def __init__(self, api_client: Incomplete | None = None) -> None: ...
    def delete_whatsapp_campaign(self, campaign_id, **kwargs): ...
    def delete_whatsapp_campaign_with_http_info(self, campaign_id, **kwargs): ...
    def get_whatsapp_campaign(self, campaign_id, **kwargs): ...
    def get_whatsapp_campaign_with_http_info(self, campaign_id, **kwargs): ...
    def get_whatsapp_templates(self, **kwargs): ...
    def get_whatsapp_templates_with_http_info(self, **kwargs): ...
