from _typeshed import Incomplete

class AbTestVersionStats:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, version_a: Incomplete | None = None, version_b: Incomplete | None = None) -> None: ...
    @property
    def version_a(self): ...
    @version_a.setter
    def version_a(self, version_a) -> None: ...
    @property
    def version_b(self): ...
    @version_b.setter
    def version_b(self, version_b) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
