from _typeshed import Incomplete

class AbTestVersionClicksInner:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, link: Incomplete | None = None, clicks_count: Incomplete | None = None, click_rate: Incomplete | None = None) -> None: ...
    @property
    def link(self): ...
    @link.setter
    def link(self, link) -> None: ...
    @property
    def clicks_count(self): ...
    @clicks_count.setter
    def clicks_count(self, clicks_count) -> None: ...
    @property
    def click_rate(self): ...
    @click_rate.setter
    def click_rate(self, click_rate) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
