from _typeshed import Incomplete

class AddContactToList:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, emails: Incomplete | None = None, ids: Incomplete | None = None) -> None: ...
    @property
    def emails(self): ...
    @emails.setter
    def emails(self, emails) -> None: ...
    @property
    def ids(self): ...
    @ids.setter
    def ids(self, ids) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
