from _typeshed import Incomplete

class Body5:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, link_contact_ids: Incomplete | None = None, unlink_contact_ids: Incomplete | None = None, link_company_ids: Incomplete | None = None, unlink_company_ids: Incomplete | None = None) -> None: ...
    @property
    def link_contact_ids(self): ...
    @link_contact_ids.setter
    def link_contact_ids(self, link_contact_ids) -> None: ...
    @property
    def unlink_contact_ids(self): ...
    @unlink_contact_ids.setter
    def unlink_contact_ids(self, unlink_contact_ids) -> None: ...
    @property
    def link_company_ids(self): ...
    @link_company_ids.setter
    def link_company_ids(self, link_company_ids) -> None: ...
    @property
    def unlink_company_ids(self): ...
    @unlink_company_ids.setter
    def unlink_company_ids(self, unlink_company_ids) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
