from _typeshed import Incomplete

class Body8:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, visitor_id: Incomplete | None = None, text: Incomplete | None = None, agent_id: Incomplete | None = None, received_from: Incomplete | None = None, agent_email: Incomplete | None = None, agent_name: Incomplete | None = None) -> None: ...
    @property
    def visitor_id(self): ...
    @visitor_id.setter
    def visitor_id(self, visitor_id) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, text) -> None: ...
    @property
    def agent_id(self): ...
    @agent_id.setter
    def agent_id(self, agent_id) -> None: ...
    @property
    def received_from(self): ...
    @received_from.setter
    def received_from(self, received_from) -> None: ...
    @property
    def agent_email(self): ...
    @agent_email.setter
    def agent_email(self, agent_email) -> None: ...
    @property
    def agent_name(self): ...
    @agent_name.setter
    def agent_name(self, agent_name) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
