from _typeshed import Incomplete

class Body10:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, visitor_id: Incomplete | None = None, text: Incomplete | None = None, agent_id: Incomplete | None = None, group_id: Incomplete | None = None) -> None: ...
    @property
    def visitor_id(self): ...
    @visitor_id.setter
    def visitor_id(self, visitor_id) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, text) -> None: ...
    @property
    def agent_id(self): ...
    @agent_id.setter
    def agent_id(self, agent_id) -> None: ...
    @property
    def group_id(self): ...
    @group_id.setter
    def group_id(self, group_id) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
