from _typeshed import Incomplete

class Body11:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, text: Incomplete | None = None) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, text) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
