from _typeshed import Incomplete

class Body2:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, link_contact_ids: Incomplete | None = None, unlink_contact_ids: Incomplete | None = None, link_deals_ids: Incomplete | None = None, unlink_deals_ids: Incomplete | None = None) -> None: ...
    @property
    def link_contact_ids(self): ...
    @link_contact_ids.setter
    def link_contact_ids(self, link_contact_ids) -> None: ...
    @property
    def unlink_contact_ids(self): ...
    @unlink_contact_ids.setter
    def unlink_contact_ids(self, unlink_contact_ids) -> None: ...
    @property
    def link_deals_ids(self): ...
    @link_deals_ids.setter
    def link_deals_ids(self, link_deals_ids) -> None: ...
    @property
    def unlink_deals_ids(self): ...
    @unlink_deals_ids.setter
    def unlink_deals_ids(self, unlink_deals_ids) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
