from _typeshed import Incomplete

class Body6:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, name: Incomplete | None = None, duration: Incomplete | None = None, task_type_id: Incomplete | None = None, _date: Incomplete | None = None, notes: Incomplete | None = None, done: Incomplete | None = None, assign_to_id: Incomplete | None = None, contacts_ids: Incomplete | None = None, deals_ids: Incomplete | None = None, companies_ids: Incomplete | None = None, reminder: Incomplete | None = None) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def duration(self): ...
    @duration.setter
    def duration(self, duration) -> None: ...
    @property
    def task_type_id(self): ...
    @task_type_id.setter
    def task_type_id(self, task_type_id) -> None: ...
    @property
    def notes(self): ...
    @notes.setter
    def notes(self, notes) -> None: ...
    @property
    def done(self): ...
    @done.setter
    def done(self, done) -> None: ...
    @property
    def assign_to_id(self): ...
    @assign_to_id.setter
    def assign_to_id(self, assign_to_id) -> None: ...
    @property
    def contacts_ids(self): ...
    @contacts_ids.setter
    def contacts_ids(self, contacts_ids) -> None: ...
    @property
    def deals_ids(self): ...
    @deals_ids.setter
    def deals_ids(self, deals_ids) -> None: ...
    @property
    def companies_ids(self): ...
    @companies_ids.setter
    def companies_ids(self, companies_ids) -> None: ...
    @property
    def reminder(self): ...
    @reminder.setter
    def reminder(self, reminder) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
