from _typeshed import Incomplete

class Company:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, attributes: Incomplete | None = None, linked_contacts_ids: Incomplete | None = None, linked_deals_ids: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def attributes(self): ...
    @attributes.setter
    def attributes(self, attributes) -> None: ...
    @property
    def linked_contacts_ids(self): ...
    @linked_contacts_ids.setter
    def linked_contacts_ids(self, linked_contacts_ids) -> None: ...
    @property
    def linked_deals_ids(self): ...
    @linked_deals_ids.setter
    def linked_deals_ids(self, linked_deals_ids) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
