from _typeshed import Incomplete

class Contact:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, virtual_next_task: Incomplete | None = None, email: Incomplete | None = None, assign_to_id: Incomplete | None = None, contacts_id: Incomplete | None = None, crm_lists: Incomplete | None = None, attributes: Incomplete | None = None, created_at: Incomplete | None = None, updated_at: Incomplete | None = None) -> None: ...
    @property
    def virtual_next_task(self): ...
    @virtual_next_task.setter
    def virtual_next_task(self, virtual_next_task) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def assign_to_id(self): ...
    @assign_to_id.setter
    def assign_to_id(self, assign_to_id) -> None: ...
    @property
    def contacts_id(self): ...
    @contacts_id.setter
    def contacts_id(self, contacts_id) -> None: ...
    @property
    def crm_lists(self): ...
    @crm_lists.setter
    def crm_lists(self, crm_lists) -> None: ...
    @property
    def attributes(self): ...
    @attributes.setter
    def attributes(self, attributes) -> None: ...
    @property
    def created_at(self): ...
    @created_at.setter
    def created_at(self, created_at) -> None: ...
    @property
    def updated_at(self): ...
    @updated_at.setter
    def updated_at(self, updated_at) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
