from _typeshed import Incomplete

class ConversationsMessage:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, type: Incomplete | None = None, text: Incomplete | None = None, visitor_id: Incomplete | None = None, agent_id: Incomplete | None = None, agent_name: Incomplete | None = None, created_at: Incomplete | None = None, is_pushed: Incomplete | None = None, received_from: Incomplete | None = None, file: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def type(self): ...
    @type.setter
    def type(self, type) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, text) -> None: ...
    @property
    def visitor_id(self): ...
    @visitor_id.setter
    def visitor_id(self, visitor_id) -> None: ...
    @property
    def agent_id(self): ...
    @agent_id.setter
    def agent_id(self, agent_id) -> None: ...
    @property
    def agent_name(self): ...
    @agent_name.setter
    def agent_name(self, agent_name) -> None: ...
    @property
    def created_at(self): ...
    @created_at.setter
    def created_at(self, created_at) -> None: ...
    @property
    def is_pushed(self): ...
    @is_pushed.setter
    def is_pushed(self, is_pushed) -> None: ...
    @property
    def received_from(self): ...
    @received_from.setter
    def received_from(self, received_from) -> None: ...
    @property
    def file(self): ...
    @file.setter
    def file(self, file) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
