from _typeshed import Incomplete

class ConversationsMessageFile:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, filename: Incomplete | None = None, size: Incomplete | None = None, is_image: Incomplete | None = None, url: Incomplete | None = None, image_info: Incomplete | None = None) -> None: ...
    @property
    def filename(self): ...
    @filename.setter
    def filename(self, filename) -> None: ...
    @property
    def size(self): ...
    @size.setter
    def size(self, size) -> None: ...
    @property
    def is_image(self): ...
    @is_image.setter
    def is_image(self, is_image) -> None: ...
    @property
    def url(self): ...
    @url.setter
    def url(self, url) -> None: ...
    @property
    def image_info(self): ...
    @image_info.setter
    def image_info(self, image_info) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
