from _typeshed import Incomplete

class ConversationsMessageFileImageInfo:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, width: Incomplete | None = None, height: Incomplete | None = None, preview_url: Incomplete | None = None) -> None: ...
    @property
    def width(self): ...
    @width.setter
    def width(self, width) -> None: ...
    @property
    def height(self): ...
    @height.setter
    def height(self, height) -> None: ...
    @property
    def preview_url(self): ...
    @preview_url.setter
    def preview_url(self, preview_url) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
