from _typeshed import Incomplete

class CreateSubAccount:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, company_name: Incomplete | None = None, email: Incomplete | None = None, language: Incomplete | None = None, timezone: Incomplete | None = None) -> None: ...
    @property
    def company_name(self): ...
    @company_name.setter
    def company_name(self, company_name) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def language(self): ...
    @language.setter
    def language(self, language) -> None: ...
    @property
    def timezone(self): ...
    @timezone.setter
    def timezone(self, timezone) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
