from _typeshed import Incomplete

class CreateDoiContact:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, email: Incomplete | None = None, attributes: Incomplete | None = None, include_list_ids: Incomplete | None = None, exclude_list_ids: Incomplete | None = None, template_id: Incomplete | None = None, redirection_url: Incomplete | None = None) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def attributes(self): ...
    @attributes.setter
    def attributes(self, attributes) -> None: ...
    @property
    def include_list_ids(self): ...
    @include_list_ids.setter
    def include_list_ids(self, include_list_ids) -> None: ...
    @property
    def exclude_list_ids(self): ...
    @exclude_list_ids.setter
    def exclude_list_ids(self, exclude_list_ids) -> None: ...
    @property
    def template_id(self): ...
    @template_id.setter
    def template_id(self, template_id) -> None: ...
    @property
    def redirection_url(self): ...
    @redirection_url.setter
    def redirection_url(self, redirection_url) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
