from _typeshed import Incomplete

class CreateSmtpEmail:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, message_id: Incomplete | None = None, message_ids: Incomplete | None = None) -> None: ...
    @property
    def message_id(self): ...
    @message_id.setter
    def message_id(self, message_id) -> None: ...
    @property
    def message_ids(self): ...
    @message_ids.setter
    def message_ids(self, message_ids) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
