from _typeshed import Incomplete

class CreateUpdateProduct:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, name: Incomplete | None = None, url: Incomplete | None = None, image_url: Incomplete | None = None, sku: Incomplete | None = None, price: Incomplete | None = None, categories: Incomplete | None = None, parent_id: Incomplete | None = None, meta_info: Incomplete | None = None, update_enabled: bool = False, deleted_at: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def url(self): ...
    @url.setter
    def url(self, url) -> None: ...
    @property
    def image_url(self): ...
    @image_url.setter
    def image_url(self, image_url) -> None: ...
    @property
    def sku(self): ...
    @sku.setter
    def sku(self, sku) -> None: ...
    @property
    def price(self): ...
    @price.setter
    def price(self, price) -> None: ...
    @property
    def categories(self): ...
    @categories.setter
    def categories(self, categories) -> None: ...
    @property
    def parent_id(self): ...
    @parent_id.setter
    def parent_id(self, parent_id) -> None: ...
    @property
    def meta_info(self): ...
    @meta_info.setter
    def meta_info(self, meta_info) -> None: ...
    @property
    def update_enabled(self): ...
    @update_enabled.setter
    def update_enabled(self, update_enabled) -> None: ...
    @property
    def deleted_at(self): ...
    @deleted_at.setter
    def deleted_at(self, deleted_at) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
