from _typeshed import Incomplete

class CreatedBatchId:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, batch_id: Incomplete | None = None) -> None: ...
    @property
    def batch_id(self): ...
    @batch_id.setter
    def batch_id(self, batch_id) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
