from _typeshed import Incomplete

class CreatedProcessId:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, process_id: Incomplete | None = None) -> None: ...
    @property
    def process_id(self): ...
    @process_id.setter
    def process_id(self, process_id) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
