from _typeshed import Incomplete

class CreateReseller:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, auth_key: Incomplete | None = None, id: Incomplete | None = None) -> None: ...
    @property
    def auth_key(self): ...
    @auth_key.setter
    def auth_key(self, auth_key) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
