from _typeshed import Incomplete

class CreateAttributeEnumeration:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, value: Incomplete | None = None, label: Incomplete | None = None) -> None: ...
    @property
    def value(self): ...
    @value.setter
    def value(self, value) -> None: ...
    @property
    def label(self): ...
    @label.setter
    def label(self, label) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
