from _typeshed import Incomplete

class CreateUpdateBatchCategory:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, categories: Incomplete | None = None, update_enabled: Incomplete | None = None) -> None: ...
    @property
    def categories(self): ...
    @categories.setter
    def categories(self, categories) -> None: ...
    @property
    def update_enabled(self): ...
    @update_enabled.setter
    def update_enabled(self, update_enabled) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
