from _typeshed import Incomplete

class CreateSmtpTemplate:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, tag: Incomplete | None = None, sender: Incomplete | None = None, template_name: Incomplete | None = None, html_content: Incomplete | None = None, html_url: Incomplete | None = None, subject: Incomplete | None = None, reply_to: Incomplete | None = None, to_field: Incomplete | None = None, attachment_url: Incomplete | None = None, is_active: Incomplete | None = None) -> None: ...
    @property
    def tag(self): ...
    @tag.setter
    def tag(self, tag) -> None: ...
    @property
    def sender(self): ...
    @sender.setter
    def sender(self, sender) -> None: ...
    @property
    def template_name(self): ...
    @template_name.setter
    def template_name(self, template_name) -> None: ...
    @property
    def html_content(self): ...
    @html_content.setter
    def html_content(self, html_content) -> None: ...
    @property
    def html_url(self): ...
    @html_url.setter
    def html_url(self, html_url) -> None: ...
    @property
    def subject(self): ...
    @subject.setter
    def subject(self, subject) -> None: ...
    @property
    def reply_to(self): ...
    @reply_to.setter
    def reply_to(self, reply_to) -> None: ...
    @property
    def to_field(self): ...
    @to_field.setter
    def to_field(self, to_field) -> None: ...
    @property
    def attachment_url(self): ...
    @attachment_url.setter
    def attachment_url(self, attachment_url) -> None: ...
    @property
    def is_active(self): ...
    @is_active.setter
    def is_active(self, is_active) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
