from _typeshed import Incomplete

class CreateApiKeyResponse:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, status: Incomplete | None = None, key: Incomplete | None = None) -> None: ...
    @property
    def status(self): ...
    @status.setter
    def status(self, status) -> None: ...
    @property
    def key(self): ...
    @key.setter
    def key(self, key) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
