from _typeshed import Incomplete

class CreateUpdateBatchProducts:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, products: Incomplete | None = None, update_enabled: Incomplete | None = None) -> None: ...
    @property
    def products(self): ...
    @products.setter
    def products(self, products) -> None: ...
    @property
    def update_enabled(self): ...
    @update_enabled.setter
    def update_enabled(self, update_enabled) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
