from _typeshed import Incomplete

class CreateSenderModel:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, spf_error: Incomplete | None = None, dkim_error: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def spf_error(self): ...
    @spf_error.setter
    def spf_error(self, spf_error) -> None: ...
    @property
    def dkim_error(self): ...
    @dkim_error.setter
    def dkim_error(self, dkim_error) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
