from _typeshed import Incomplete

class CreateUpdateBatchCategoryModel:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, created_count: Incomplete | None = None, updated_count: Incomplete | None = None) -> None: ...
    @property
    def created_count(self): ...
    @created_count.setter
    def created_count(self, created_count) -> None: ...
    @property
    def updated_count(self): ...
    @updated_count.setter
    def updated_count(self, updated_count) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
