from _typeshed import Incomplete

class DealAttributesInner:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, internal_name: Incomplete | None = None, label: Incomplete | None = None, attribute_type_name: Incomplete | None = None, attribute_options: Incomplete | None = None, is_required: Incomplete | None = None) -> None: ...
    @property
    def internal_name(self): ...
    @internal_name.setter
    def internal_name(self, internal_name) -> None: ...
    @property
    def label(self): ...
    @label.setter
    def label(self, label) -> None: ...
    @property
    def attribute_type_name(self): ...
    @attribute_type_name.setter
    def attribute_type_name(self, attribute_type_name) -> None: ...
    @property
    def attribute_options(self): ...
    @attribute_options.setter
    def attribute_options(self, attribute_options) -> None: ...
    @property
    def is_required(self): ...
    @is_required.setter
    def is_required(self, is_required) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
