from _typeshed import Incomplete

class DeleteHardbounces:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, start_date: Incomplete | None = None, end_date: Incomplete | None = None, contact_email: Incomplete | None = None) -> None: ...
    @property
    def start_date(self): ...
    @start_date.setter
    def start_date(self, start_date) -> None: ...
    @property
    def end_date(self): ...
    @end_date.setter
    def end_date(self, end_date) -> None: ...
    @property
    def contact_email(self): ...
    @contact_email.setter
    def contact_email(self, contact_email) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
