from _typeshed import Incomplete

class FileData:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, name: Incomplete | None = None, author_id: Incomplete | None = None, contact_id: Incomplete | None = None, deal_id: Incomplete | None = None, company_id: Incomplete | None = None, size: Incomplete | None = None, created_at: Incomplete | None = None) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def author_id(self): ...
    @author_id.setter
    def author_id(self, author_id) -> None: ...
    @property
    def contact_id(self): ...
    @contact_id.setter
    def contact_id(self, contact_id) -> None: ...
    @property
    def deal_id(self): ...
    @deal_id.setter
    def deal_id(self, deal_id) -> None: ...
    @property
    def company_id(self): ...
    @company_id.setter
    def company_id(self, company_id) -> None: ...
    @property
    def size(self): ...
    @size.setter
    def size(self, size) -> None: ...
    @property
    def created_at(self): ...
    @created_at.setter
    def created_at(self, created_at) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
