from _typeshed import Incomplete

class GetAccountPlan:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, type: Incomplete | None = None, credits_type: Incomplete | None = None, credits: Incomplete | None = None, start_date: Incomplete | None = None, end_date: Incomplete | None = None, user_limit: Incomplete | None = None) -> None: ...
    @property
    def type(self): ...
    @type.setter
    def type(self, type) -> None: ...
    @property
    def credits_type(self): ...
    @credits_type.setter
    def credits_type(self, credits_type) -> None: ...
    @property
    def credits(self): ...
    @credits.setter
    def credits(self, credits) -> None: ...
    @property
    def start_date(self): ...
    @start_date.setter
    def start_date(self, start_date) -> None: ...
    @property
    def end_date(self): ...
    @end_date.setter
    def end_date(self, end_date) -> None: ...
    @property
    def user_limit(self): ...
    @user_limit.setter
    def user_limit(self, user_limit) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
