from _typeshed import Incomplete

class GetChildInfo:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, email: Incomplete | None = None, first_name: Incomplete | None = None, last_name: Incomplete | None = None, company_name: Incomplete | None = None, credits: Incomplete | None = None, statistics: Incomplete | None = None, password: Incomplete | None = None, ips: Incomplete | None = None, api_keys: Incomplete | None = None) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def first_name(self): ...
    @first_name.setter
    def first_name(self, first_name) -> None: ...
    @property
    def last_name(self): ...
    @last_name.setter
    def last_name(self, last_name) -> None: ...
    @property
    def company_name(self): ...
    @company_name.setter
    def company_name(self, company_name) -> None: ...
    @property
    def credits(self): ...
    @credits.setter
    def credits(self, credits) -> None: ...
    @property
    def statistics(self): ...
    @statistics.setter
    def statistics(self, statistics) -> None: ...
    @property
    def password(self): ...
    @password.setter
    def password(self, password) -> None: ...
    @property
    def ips(self): ...
    @ips.setter
    def ips(self, ips) -> None: ...
    @property
    def api_keys(self): ...
    @api_keys.setter
    def api_keys(self, api_keys) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
