from _typeshed import Incomplete

class GetExtendedContactDetailsStatisticsLinks:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, count: Incomplete | None = None, event_time: Incomplete | None = None, ip: Incomplete | None = None, url: Incomplete | None = None) -> None: ...
    @property
    def count(self): ...
    @count.setter
    def count(self, count) -> None: ...
    @property
    def event_time(self): ...
    @event_time.setter
    def event_time(self, event_time) -> None: ...
    @property
    def ip(self): ...
    @ip.setter
    def ip(self, ip) -> None: ...
    @property
    def url(self): ...
    @url.setter
    def url(self, url) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
