from _typeshed import Incomplete

class GetTransacEmailsListTransactionalEmails:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, email: Incomplete | None = None, subject: Incomplete | None = None, template_id: Incomplete | None = None, message_id: Incomplete | None = None, uuid: Incomplete | None = None, _date: Incomplete | None = None, _from: Incomplete | None = None, tags: Incomplete | None = None) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def subject(self): ...
    @subject.setter
    def subject(self, subject) -> None: ...
    @property
    def template_id(self): ...
    @template_id.setter
    def template_id(self, template_id) -> None: ...
    @property
    def message_id(self): ...
    @message_id.setter
    def message_id(self, message_id) -> None: ...
    @property
    def uuid(self): ...
    @uuid.setter
    def uuid(self, uuid) -> None: ...
    @property
    def tags(self): ...
    @tags.setter
    def tags(self, tags) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
