from _typeshed import Incomplete

class GetIp:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, ip: Incomplete | None = None, active: Incomplete | None = None, domain: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def ip(self): ...
    @ip.setter
    def ip(self, ip) -> None: ...
    @property
    def active(self): ...
    @active.setter
    def active(self, active) -> None: ...
    @property
    def domain(self): ...
    @domain.setter
    def domain(self, domain) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
