from _typeshed import Incomplete

class GetFolder:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, name: Incomplete | None = None, total_blacklisted: Incomplete | None = None, total_subscribers: Incomplete | None = None, unique_subscribers: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def total_blacklisted(self): ...
    @total_blacklisted.setter
    def total_blacklisted(self, total_blacklisted) -> None: ...
    @property
    def total_subscribers(self): ...
    @total_subscribers.setter
    def total_subscribers(self, total_subscribers) -> None: ...
    @property
    def unique_subscribers(self): ...
    @unique_subscribers.setter
    def unique_subscribers(self, unique_subscribers) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
