from _typeshed import Incomplete

class GetClient:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, email: Incomplete | None = None, first_name: Incomplete | None = None, last_name: Incomplete | None = None, company_name: Incomplete | None = None) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def first_name(self): ...
    @first_name.setter
    def first_name(self, first_name) -> None: ...
    @property
    def last_name(self): ...
    @last_name.setter
    def last_name(self, last_name) -> None: ...
    @property
    def company_name(self): ...
    @company_name.setter
    def company_name(self, company_name) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
