from _typeshed import Incomplete

class GetReports:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, reports: Incomplete | None = None) -> None: ...
    @property
    def reports(self): ...
    @reports.setter
    def reports(self, reports) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
