from _typeshed import Incomplete

class GetProductDetails:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, name: Incomplete | None = None, created_at: Incomplete | None = None, modified_at: Incomplete | None = None, url: Incomplete | None = None, image_url: Incomplete | None = None, sku: Incomplete | None = None, price: Incomplete | None = None, categories: Incomplete | None = None, parent_id: Incomplete | None = None, s3_original: Incomplete | None = None, s3_thumb_analytics: Incomplete | None = None, meta_info: Incomplete | None = None, s3_thumb_editor: Incomplete | None = None, is_deleted: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def created_at(self): ...
    @created_at.setter
    def created_at(self, created_at) -> None: ...
    @property
    def modified_at(self): ...
    @modified_at.setter
    def modified_at(self, modified_at) -> None: ...
    @property
    def url(self): ...
    @url.setter
    def url(self, url) -> None: ...
    @property
    def image_url(self): ...
    @image_url.setter
    def image_url(self, image_url) -> None: ...
    @property
    def sku(self): ...
    @sku.setter
    def sku(self, sku) -> None: ...
    @property
    def price(self): ...
    @price.setter
    def price(self, price) -> None: ...
    @property
    def categories(self): ...
    @categories.setter
    def categories(self, categories) -> None: ...
    @property
    def parent_id(self): ...
    @parent_id.setter
    def parent_id(self, parent_id) -> None: ...
    @property
    def s3_original(self): ...
    @s3_original.setter
    def s3_original(self, s3_original) -> None: ...
    @property
    def s3_thumb_analytics(self): ...
    @s3_thumb_analytics.setter
    def s3_thumb_analytics(self, s3_thumb_analytics) -> None: ...
    @property
    def meta_info(self): ...
    @meta_info.setter
    def meta_info(self, meta_info) -> None: ...
    @property
    def s3_thumb_editor(self): ...
    @s3_thumb_editor.setter
    def s3_thumb_editor(self, s3_thumb_editor) -> None: ...
    @property
    def is_deleted(self): ...
    @is_deleted.setter
    def is_deleted(self, is_deleted) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
