from _typeshed import Incomplete

class GetSmtpTemplateOverview:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, name: Incomplete | None = None, subject: Incomplete | None = None, is_active: Incomplete | None = None, test_sent: Incomplete | None = None, sender: Incomplete | None = None, reply_to: Incomplete | None = None, to_field: Incomplete | None = None, tag: Incomplete | None = None, html_content: Incomplete | None = None, created_at: Incomplete | None = None, modified_at: Incomplete | None = None, doi_template: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def subject(self): ...
    @subject.setter
    def subject(self, subject) -> None: ...
    @property
    def is_active(self): ...
    @is_active.setter
    def is_active(self, is_active) -> None: ...
    @property
    def test_sent(self): ...
    @test_sent.setter
    def test_sent(self, test_sent) -> None: ...
    @property
    def sender(self): ...
    @sender.setter
    def sender(self, sender) -> None: ...
    @property
    def reply_to(self): ...
    @reply_to.setter
    def reply_to(self, reply_to) -> None: ...
    @property
    def to_field(self): ...
    @to_field.setter
    def to_field(self, to_field) -> None: ...
    @property
    def tag(self): ...
    @tag.setter
    def tag(self, tag) -> None: ...
    @property
    def html_content(self): ...
    @html_content.setter
    def html_content(self, html_content) -> None: ...
    @property
    def created_at(self): ...
    @created_at.setter
    def created_at(self, created_at) -> None: ...
    @property
    def modified_at(self): ...
    @modified_at.setter
    def modified_at(self, modified_at) -> None: ...
    @property
    def doi_template(self): ...
    @doi_template.setter
    def doi_template(self, doi_template) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
