from _typeshed import Incomplete

class GetTransacAggregatedSmsReport:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, range: Incomplete | None = None, requests: Incomplete | None = None, delivered: Incomplete | None = None, hard_bounces: Incomplete | None = None, soft_bounces: Incomplete | None = None, blocked: Incomplete | None = None, unsubscribed: Incomplete | None = None, replied: Incomplete | None = None, accepted: Incomplete | None = None, rejected: Incomplete | None = None) -> None: ...
    @property
    def range(self): ...
    @range.setter
    def range(self, range) -> None: ...
    @property
    def requests(self): ...
    @requests.setter
    def requests(self, requests) -> None: ...
    @property
    def delivered(self): ...
    @delivered.setter
    def delivered(self, delivered) -> None: ...
    @property
    def hard_bounces(self): ...
    @hard_bounces.setter
    def hard_bounces(self, hard_bounces) -> None: ...
    @property
    def soft_bounces(self): ...
    @soft_bounces.setter
    def soft_bounces(self, soft_bounces) -> None: ...
    @property
    def blocked(self): ...
    @blocked.setter
    def blocked(self, blocked) -> None: ...
    @property
    def unsubscribed(self): ...
    @unsubscribed.setter
    def unsubscribed(self, unsubscribed) -> None: ...
    @property
    def replied(self): ...
    @replied.setter
    def replied(self, replied) -> None: ...
    @property
    def accepted(self): ...
    @accepted.setter
    def accepted(self, accepted) -> None: ...
    @property
    def rejected(self): ...
    @rejected.setter
    def rejected(self, rejected) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
