from _typeshed import Incomplete

class GetChildDomain:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, domain: Incomplete | None = None, active: Incomplete | None = None) -> None: ...
    @property
    def domain(self): ...
    @domain.setter
    def domain(self, domain) -> None: ...
    @property
    def active(self): ...
    @active.setter
    def active(self, active) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
