from _typeshed import Incomplete

class GetSendersList:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, senders: Incomplete | None = None) -> None: ...
    @property
    def senders(self): ...
    @senders.setter
    def senders(self, senders) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
