from _typeshed import Incomplete

class GetChildrenList:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, children: Incomplete | None = None, count: Incomplete | None = None) -> None: ...
    @property
    def children(self): ...
    @children.setter
    def children(self, children) -> None: ...
    @property
    def count(self): ...
    @count.setter
    def count(self, count) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
