from _typeshed import Incomplete

class GetIps:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, ips: Incomplete | None = None) -> None: ...
    @property
    def ips(self): ...
    @ips.setter
    def ips(self, ips) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
