from _typeshed import Incomplete

class GetCategories:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, categories: Incomplete | None = None, count: Incomplete | None = None) -> None: ...
    @property
    def categories(self): ...
    @categories.setter
    def categories(self, categories) -> None: ...
    @property
    def count(self): ...
    @count.setter
    def count(self, count) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
