from _typeshed import Incomplete

class GetStatsByDevice:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, desktop: Incomplete | None = None, mobile: Incomplete | None = None, tablet: Incomplete | None = None, unknown: Incomplete | None = None) -> None: ...
    @property
    def desktop(self): ...
    @desktop.setter
    def desktop(self, desktop) -> None: ...
    @property
    def mobile(self): ...
    @mobile.setter
    def mobile(self, mobile) -> None: ...
    @property
    def tablet(self): ...
    @tablet.setter
    def tablet(self, tablet) -> None: ...
    @property
    def unknown(self): ...
    @unknown.setter
    def unknown(self, unknown) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
