from _typeshed import Incomplete

class GetSmsCampaignOverview:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, name: Incomplete | None = None, status: Incomplete | None = None, content: Incomplete | None = None, scheduled_at: Incomplete | None = None, sender: Incomplete | None = None, created_at: Incomplete | None = None, modified_at: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def status(self): ...
    @status.setter
    def status(self, status) -> None: ...
    @property
    def content(self): ...
    @content.setter
    def content(self, content) -> None: ...
    @property
    def scheduled_at(self): ...
    @scheduled_at.setter
    def scheduled_at(self, scheduled_at) -> None: ...
    @property
    def sender(self): ...
    @sender.setter
    def sender(self, sender) -> None: ...
    @property
    def created_at(self): ...
    @created_at.setter
    def created_at(self, created_at) -> None: ...
    @property
    def modified_at(self): ...
    @modified_at.setter
    def modified_at(self, modified_at) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
