from _typeshed import Incomplete

class GetExtendedList:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, name: Incomplete | None = None, total_blacklisted: Incomplete | None = None, total_subscribers: Incomplete | None = None, unique_subscribers: Incomplete | None = None, folder_id: Incomplete | None = None, created_at: Incomplete | None = None, campaign_stats: Incomplete | None = None, dynamic_list: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def total_blacklisted(self): ...
    @total_blacklisted.setter
    def total_blacklisted(self, total_blacklisted) -> None: ...
    @property
    def total_subscribers(self): ...
    @total_subscribers.setter
    def total_subscribers(self, total_subscribers) -> None: ...
    @property
    def unique_subscribers(self): ...
    @unique_subscribers.setter
    def unique_subscribers(self, unique_subscribers) -> None: ...
    @property
    def folder_id(self): ...
    @folder_id.setter
    def folder_id(self, folder_id) -> None: ...
    @property
    def created_at(self): ...
    @created_at.setter
    def created_at(self, created_at) -> None: ...
    @property
    def campaign_stats(self): ...
    @campaign_stats.setter
    def campaign_stats(self, campaign_stats) -> None: ...
    @property
    def dynamic_list(self): ...
    @dynamic_list.setter
    def dynamic_list(self, dynamic_list) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
