from _typeshed import Incomplete

class GetAllExternalFeeds:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, count: Incomplete | None = None, feeds: Incomplete | None = None) -> None: ...
    @property
    def count(self): ...
    @count.setter
    def count(self, count) -> None: ...
    @property
    def feeds(self): ...
    @feeds.setter
    def feeds(self, feeds) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
