from _typeshed import Incomplete

class GetAccount:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, email: Incomplete | None = None, first_name: Incomplete | None = None, last_name: Incomplete | None = None, company_name: Incomplete | None = None, address: Incomplete | None = None, plan: Incomplete | None = None, relay: Incomplete | None = None, marketing_automation: Incomplete | None = None) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def first_name(self): ...
    @first_name.setter
    def first_name(self, first_name) -> None: ...
    @property
    def last_name(self): ...
    @last_name.setter
    def last_name(self, last_name) -> None: ...
    @property
    def company_name(self): ...
    @company_name.setter
    def company_name(self, company_name) -> None: ...
    @property
    def address(self): ...
    @address.setter
    def address(self, address) -> None: ...
    @property
    def plan(self): ...
    @plan.setter
    def plan(self, plan) -> None: ...
    @property
    def relay(self): ...
    @relay.setter
    def relay(self, relay) -> None: ...
    @property
    def marketing_automation(self): ...
    @marketing_automation.setter
    def marketing_automation(self, marketing_automation) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
