from _typeshed import Incomplete

class GetWebhooks:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, webhooks: Incomplete | None = None) -> None: ...
    @property
    def webhooks(self): ...
    @webhooks.setter
    def webhooks(self, webhooks) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
