from _typeshed import Incomplete

class GetExtendedClientAddress:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, street: Incomplete | None = None, city: Incomplete | None = None, zip_code: Incomplete | None = None, country: Incomplete | None = None) -> None: ...
    @property
    def street(self): ...
    @street.setter
    def street(self, street) -> None: ...
    @property
    def city(self): ...
    @city.setter
    def city(self, city) -> None: ...
    @property
    def zip_code(self): ...
    @zip_code.setter
    def zip_code(self, zip_code) -> None: ...
    @property
    def country(self): ...
    @country.setter
    def country(self, country) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
