from _typeshed import Incomplete

class GetBlockedDomains:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, domains: Incomplete | None = None) -> None: ...
    @property
    def domains(self): ...
    @domains.setter
    def domains(self, domains) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
