from _typeshed import Incomplete

class GetCampaignStats:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, list_id: Incomplete | None = None, unique_clicks: Incomplete | None = None, clickers: Incomplete | None = None, complaints: Incomplete | None = None, delivered: Incomplete | None = None, sent: Incomplete | None = None, soft_bounces: Incomplete | None = None, hard_bounces: Incomplete | None = None, unique_views: Incomplete | None = None, trackable_views: Incomplete | None = None, trackable_views_rate: Incomplete | None = None, estimated_views: Incomplete | None = None, unsubscriptions: Incomplete | None = None, viewed: Incomplete | None = None, deferred: Incomplete | None = None, return_bounce: Incomplete | None = None) -> None: ...
    @property
    def list_id(self): ...
    @list_id.setter
    def list_id(self, list_id) -> None: ...
    @property
    def unique_clicks(self): ...
    @unique_clicks.setter
    def unique_clicks(self, unique_clicks) -> None: ...
    @property
    def clickers(self): ...
    @clickers.setter
    def clickers(self, clickers) -> None: ...
    @property
    def complaints(self): ...
    @complaints.setter
    def complaints(self, complaints) -> None: ...
    @property
    def delivered(self): ...
    @delivered.setter
    def delivered(self, delivered) -> None: ...
    @property
    def sent(self): ...
    @sent.setter
    def sent(self, sent) -> None: ...
    @property
    def soft_bounces(self): ...
    @soft_bounces.setter
    def soft_bounces(self, soft_bounces) -> None: ...
    @property
    def hard_bounces(self): ...
    @hard_bounces.setter
    def hard_bounces(self, hard_bounces) -> None: ...
    @property
    def unique_views(self): ...
    @unique_views.setter
    def unique_views(self, unique_views) -> None: ...
    @property
    def trackable_views(self): ...
    @trackable_views.setter
    def trackable_views(self, trackable_views) -> None: ...
    @property
    def trackable_views_rate(self): ...
    @trackable_views_rate.setter
    def trackable_views_rate(self, trackable_views_rate) -> None: ...
    @property
    def estimated_views(self): ...
    @estimated_views.setter
    def estimated_views(self, estimated_views) -> None: ...
    @property
    def unsubscriptions(self): ...
    @unsubscriptions.setter
    def unsubscriptions(self, unsubscriptions) -> None: ...
    @property
    def viewed(self): ...
    @viewed.setter
    def viewed(self, viewed) -> None: ...
    @property
    def deferred(self): ...
    @deferred.setter
    def deferred(self, deferred) -> None: ...
    @property
    def return_bounce(self): ...
    @return_bounce.setter
    def return_bounce(self, return_bounce) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
