from _typeshed import Incomplete

class GetExtendedContactDetailsStatisticsClicked:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, campaign_id: Incomplete | None = None, links: Incomplete | None = None) -> None: ...
    @property
    def campaign_id(self): ...
    @campaign_id.setter
    def campaign_id(self, campaign_id) -> None: ...
    @property
    def links(self): ...
    @links.setter
    def links(self, links) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
