from _typeshed import Incomplete

class GetWebhook:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, url: Incomplete | None = None, id: Incomplete | None = None, description: Incomplete | None = None, events: Incomplete | None = None, type: Incomplete | None = None, created_at: Incomplete | None = None, modified_at: Incomplete | None = None) -> None: ...
    @property
    def url(self): ...
    @url.setter
    def url(self, url) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def description(self): ...
    @description.setter
    def description(self, description) -> None: ...
    @property
    def events(self): ...
    @events.setter
    def events(self, events) -> None: ...
    @property
    def type(self): ...
    @type.setter
    def type(self, type) -> None: ...
    @property
    def created_at(self): ...
    @created_at.setter
    def created_at(self, created_at) -> None: ...
    @property
    def modified_at(self): ...
    @modified_at.setter
    def modified_at(self, modified_at) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
