from _typeshed import Incomplete

class GetInboundEmailEventsEvents:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, uuid: Incomplete | None = None, _date: Incomplete | None = None, sender: Incomplete | None = None, recipient: Incomplete | None = None) -> None: ...
    @property
    def uuid(self): ...
    @uuid.setter
    def uuid(self, uuid) -> None: ...
    @property
    def sender(self): ...
    @sender.setter
    def sender(self, sender) -> None: ...
    @property
    def recipient(self): ...
    @recipient.setter
    def recipient(self, recipient) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
