from _typeshed import Incomplete

class GetSmsCampaignStats:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, delivered: Incomplete | None = None, sent: Incomplete | None = None, processing: Incomplete | None = None, soft_bounces: Incomplete | None = None, hard_bounces: Incomplete | None = None, unsubscriptions: Incomplete | None = None, answered: Incomplete | None = None) -> None: ...
    @property
    def delivered(self): ...
    @delivered.setter
    def delivered(self, delivered) -> None: ...
    @property
    def sent(self): ...
    @sent.setter
    def sent(self, sent) -> None: ...
    @property
    def processing(self): ...
    @processing.setter
    def processing(self, processing) -> None: ...
    @property
    def soft_bounces(self): ...
    @soft_bounces.setter
    def soft_bounces(self, soft_bounces) -> None: ...
    @property
    def hard_bounces(self): ...
    @hard_bounces.setter
    def hard_bounces(self, hard_bounces) -> None: ...
    @property
    def unsubscriptions(self): ...
    @unsubscriptions.setter
    def unsubscriptions(self, unsubscriptions) -> None: ...
    @property
    def answered(self): ...
    @answered.setter
    def answered(self, answered) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
