from _typeshed import Incomplete

class GetInboundEmailEventsByUuidAttachments:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, name: Incomplete | None = None, content_type: Incomplete | None = None, content_id: Incomplete | None = None, content_length: Incomplete | None = None) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def content_type(self): ...
    @content_type.setter
    def content_type(self, content_type) -> None: ...
    @property
    def content_id(self): ...
    @content_id.setter
    def content_id(self, content_id) -> None: ...
    @property
    def content_length(self): ...
    @content_length.setter
    def content_length(self, content_length) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
