from _typeshed import Incomplete

class GetChildAccountCreationStatus:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, child_account_created: Incomplete | None = None) -> None: ...
    @property
    def child_account_created(self): ...
    @child_account_created.setter
    def child_account_created(self, child_account_created) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
