from _typeshed import Incomplete

class GetWhatsappCampaignOverview:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, campaign_name: Incomplete | None = None, campaign_status: Incomplete | None = None, scheduled_at: Incomplete | None = None, sender_number: Incomplete | None = None, stats: Incomplete | None = None, template: Incomplete | None = None, created_at: Incomplete | None = None, modified_at: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def campaign_name(self): ...
    @campaign_name.setter
    def campaign_name(self, campaign_name) -> None: ...
    @property
    def campaign_status(self): ...
    @campaign_status.setter
    def campaign_status(self, campaign_status) -> None: ...
    @property
    def scheduled_at(self): ...
    @scheduled_at.setter
    def scheduled_at(self, scheduled_at) -> None: ...
    @property
    def sender_number(self): ...
    @sender_number.setter
    def sender_number(self, sender_number) -> None: ...
    @property
    def stats(self): ...
    @stats.setter
    def stats(self, stats) -> None: ...
    @property
    def template(self): ...
    @template.setter
    def template(self, template) -> None: ...
    @property
    def created_at(self): ...
    @created_at.setter
    def created_at(self, created_at) -> None: ...
    @property
    def modified_at(self): ...
    @modified_at.setter
    def modified_at(self, modified_at) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
