from _typeshed import Incomplete

class GetSmsEventReportEvents:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, phone_number: Incomplete | None = None, _date: Incomplete | None = None, message_id: Incomplete | None = None, event: Incomplete | None = None, reason: Incomplete | None = None, reply: Incomplete | None = None, tag: Incomplete | None = None) -> None: ...
    @property
    def phone_number(self): ...
    @phone_number.setter
    def phone_number(self, phone_number) -> None: ...
    @property
    def message_id(self): ...
    @message_id.setter
    def message_id(self, message_id) -> None: ...
    @property
    def event(self): ...
    @event.setter
    def event(self, event) -> None: ...
    @property
    def reason(self): ...
    @reason.setter
    def reason(self, reason) -> None: ...
    @property
    def reply(self): ...
    @reply.setter
    def reply(self, reply) -> None: ...
    @property
    def tag(self): ...
    @tag.setter
    def tag(self, tag) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
