from _typeshed import Incomplete

class GetContacts:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, contacts: Incomplete | None = None, count: Incomplete | None = None) -> None: ...
    @property
    def contacts(self): ...
    @contacts.setter
    def contacts(self, contacts) -> None: ...
    @property
    def count(self): ...
    @count.setter
    def count(self, count) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
