from _typeshed import Incomplete

class GetContactCampaignStats:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, messages_sent: Incomplete | None = None, hard_bounces: Incomplete | None = None, soft_bounces: Incomplete | None = None, complaints: Incomplete | None = None, unsubscriptions: Incomplete | None = None, opened: Incomplete | None = None, clicked: Incomplete | None = None, transac_attributes: Incomplete | None = None, delivered: Incomplete | None = None) -> None: ...
    @property
    def messages_sent(self): ...
    @messages_sent.setter
    def messages_sent(self, messages_sent) -> None: ...
    @property
    def hard_bounces(self): ...
    @hard_bounces.setter
    def hard_bounces(self, hard_bounces) -> None: ...
    @property
    def soft_bounces(self): ...
    @soft_bounces.setter
    def soft_bounces(self, soft_bounces) -> None: ...
    @property
    def complaints(self): ...
    @complaints.setter
    def complaints(self, complaints) -> None: ...
    @property
    def unsubscriptions(self): ...
    @unsubscriptions.setter
    def unsubscriptions(self, unsubscriptions) -> None: ...
    @property
    def opened(self): ...
    @opened.setter
    def opened(self, opened) -> None: ...
    @property
    def clicked(self): ...
    @clicked.setter
    def clicked(self, clicked) -> None: ...
    @property
    def transac_attributes(self): ...
    @transac_attributes.setter
    def transac_attributes(self, transac_attributes) -> None: ...
    @property
    def delivered(self): ...
    @delivered.setter
    def delivered(self, delivered) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
