from _typeshed import Incomplete

class GetChildInfoCredits:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, email_credits: Incomplete | None = None, sms_credits: Incomplete | None = None) -> None: ...
    @property
    def email_credits(self): ...
    @email_credits.setter
    def email_credits(self, email_credits) -> None: ...
    @property
    def sms_credits(self): ...
    @sms_credits.setter
    def sms_credits(self, sms_credits) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
