from _typeshed import Incomplete

class GetTransacEmailContent:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, email: Incomplete | None = None, subject: Incomplete | None = None, template_id: Incomplete | None = None, _date: Incomplete | None = None, events: Incomplete | None = None, body: Incomplete | None = None, attachment_count: Incomplete | None = None) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def subject(self): ...
    @subject.setter
    def subject(self, subject) -> None: ...
    @property
    def template_id(self): ...
    @template_id.setter
    def template_id(self, template_id) -> None: ...
    @property
    def events(self): ...
    @events.setter
    def events(self, events) -> None: ...
    @property
    def body(self): ...
    @body.setter
    def body(self, body) -> None: ...
    @property
    def attachment_count(self): ...
    @attachment_count.setter
    def attachment_count(self, attachment_count) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
