from _typeshed import Incomplete

class GetProcesses:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, processes: Incomplete | None = None, count: Incomplete | None = None) -> None: ...
    @property
    def processes(self): ...
    @processes.setter
    def processes(self, processes) -> None: ...
    @property
    def count(self): ...
    @count.setter
    def count(self, count) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
