from _typeshed import Incomplete

class GetContactCampaignStatsUnsubscriptions:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, user_unsubscription: Incomplete | None = None, admin_unsubscription: Incomplete | None = None) -> None: ...
    @property
    def user_unsubscription(self): ...
    @user_unsubscription.setter
    def user_unsubscription(self, user_unsubscription) -> None: ...
    @property
    def admin_unsubscription(self): ...
    @admin_unsubscription.setter
    def admin_unsubscription(self, admin_unsubscription) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
