from _typeshed import Incomplete

class GetCampaignOverview:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, name: Incomplete | None = None, subject: Incomplete | None = None, type: Incomplete | None = None, status: Incomplete | None = None, scheduled_at: Incomplete | None = None, ab_testing: Incomplete | None = None, subject_a: Incomplete | None = None, subject_b: Incomplete | None = None, split_rule: Incomplete | None = None, winner_criteria: Incomplete | None = None, winner_delay: Incomplete | None = None, send_at_best_time: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def subject(self): ...
    @subject.setter
    def subject(self, subject) -> None: ...
    @property
    def type(self): ...
    @type.setter
    def type(self, type) -> None: ...
    @property
    def status(self): ...
    @status.setter
    def status(self, status) -> None: ...
    @property
    def scheduled_at(self): ...
    @scheduled_at.setter
    def scheduled_at(self, scheduled_at) -> None: ...
    @property
    def ab_testing(self): ...
    @ab_testing.setter
    def ab_testing(self, ab_testing) -> None: ...
    @property
    def subject_a(self): ...
    @subject_a.setter
    def subject_a(self, subject_a) -> None: ...
    @property
    def subject_b(self): ...
    @subject_b.setter
    def subject_b(self, subject_b) -> None: ...
    @property
    def split_rule(self): ...
    @split_rule.setter
    def split_rule(self, split_rule) -> None: ...
    @property
    def winner_criteria(self): ...
    @winner_criteria.setter
    def winner_criteria(self, winner_criteria) -> None: ...
    @property
    def winner_delay(self): ...
    @winner_delay.setter
    def winner_delay(self, winner_delay) -> None: ...
    @property
    def send_at_best_time(self): ...
    @send_at_best_time.setter
    def send_at_best_time(self, send_at_best_time) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
