from _typeshed import Incomplete

class GetInboundEmailEventsByUuid:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, received_at: Incomplete | None = None, delivered_at: Incomplete | None = None, recipient: Incomplete | None = None, sender: Incomplete | None = None, message_id: Incomplete | None = None, subject: Incomplete | None = None, attachments: Incomplete | None = None, logs: Incomplete | None = None) -> None: ...
    @property
    def received_at(self): ...
    @received_at.setter
    def received_at(self, received_at) -> None: ...
    @property
    def delivered_at(self): ...
    @delivered_at.setter
    def delivered_at(self, delivered_at) -> None: ...
    @property
    def recipient(self): ...
    @recipient.setter
    def recipient(self, recipient) -> None: ...
    @property
    def sender(self): ...
    @sender.setter
    def sender(self, sender) -> None: ...
    @property
    def message_id(self): ...
    @message_id.setter
    def message_id(self, message_id) -> None: ...
    @property
    def subject(self): ...
    @subject.setter
    def subject(self, subject) -> None: ...
    @property
    def attachments(self): ...
    @attachments.setter
    def attachments(self, attachments) -> None: ...
    @property
    def logs(self): ...
    @logs.setter
    def logs(self, logs) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
