from _typeshed import Incomplete

class GetSharedTemplateUrl:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, shared_url: Incomplete | None = None) -> None: ...
    @property
    def shared_url(self): ...
    @shared_url.setter
    def shared_url(self, shared_url) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
