from _typeshed import Incomplete

class GetContactDetails:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, email: Incomplete | None = None, id: Incomplete | None = None, email_blacklisted: Incomplete | None = None, sms_blacklisted: Incomplete | None = None, created_at: Incomplete | None = None, modified_at: Incomplete | None = None, list_ids: Incomplete | None = None, list_unsubscribed: Incomplete | None = None, attributes: Incomplete | None = None) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def email_blacklisted(self): ...
    @email_blacklisted.setter
    def email_blacklisted(self, email_blacklisted) -> None: ...
    @property
    def sms_blacklisted(self): ...
    @sms_blacklisted.setter
    def sms_blacklisted(self, sms_blacklisted) -> None: ...
    @property
    def created_at(self): ...
    @created_at.setter
    def created_at(self, created_at) -> None: ...
    @property
    def modified_at(self): ...
    @modified_at.setter
    def modified_at(self, modified_at) -> None: ...
    @property
    def list_ids(self): ...
    @list_ids.setter
    def list_ids(self, list_ids) -> None: ...
    @property
    def list_unsubscribed(self): ...
    @list_unsubscribed.setter
    def list_unsubscribed(self, list_unsubscribed) -> None: ...
    @property
    def attributes(self): ...
    @attributes.setter
    def attributes(self, attributes) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
