from _typeshed import Incomplete

class GetWhatsappEventReportEvents:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, contact_number: Incomplete | None = None, _date: Incomplete | None = None, message_id: Incomplete | None = None, event: Incomplete | None = None, reason: Incomplete | None = None, body: Incomplete | None = None, media_url: Incomplete | None = None, sender_number: Incomplete | None = None) -> None: ...
    @property
    def contact_number(self): ...
    @contact_number.setter
    def contact_number(self, contact_number) -> None: ...
    @property
    def message_id(self): ...
    @message_id.setter
    def message_id(self, message_id) -> None: ...
    @property
    def event(self): ...
    @event.setter
    def event(self, event) -> None: ...
    @property
    def reason(self): ...
    @reason.setter
    def reason(self, reason) -> None: ...
    @property
    def body(self): ...
    @body.setter
    def body(self, body) -> None: ...
    @property
    def media_url(self): ...
    @media_url.setter
    def media_url(self, media_url) -> None: ...
    @property
    def sender_number(self): ...
    @sender_number.setter
    def sender_number(self, sender_number) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
