from _typeshed import Incomplete

class GetTransacBlockedContactsContacts:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, email: Incomplete | None = None, sender_email: Incomplete | None = None, reason: Incomplete | None = None, blocked_at: Incomplete | None = None) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def sender_email(self): ...
    @sender_email.setter
    def sender_email(self, sender_email) -> None: ...
    @property
    def reason(self): ...
    @reason.setter
    def reason(self, reason) -> None: ...
    @property
    def blocked_at(self): ...
    @blocked_at.setter
    def blocked_at(self, blocked_at) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
