from _typeshed import Incomplete

class GetProducts:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, products: Incomplete | None = None, count: Incomplete | None = None) -> None: ...
    @property
    def products(self): ...
    @products.setter
    def products(self, products) -> None: ...
    @property
    def count(self): ...
    @count.setter
    def count(self, count) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
