from _typeshed import Incomplete

class GetFolderLists:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, lists: Incomplete | None = None, count: Incomplete | None = None) -> None: ...
    @property
    def lists(self): ...
    @lists.setter
    def lists(self, lists) -> None: ...
    @property
    def count(self): ...
    @count.setter
    def count(self, count) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
