from _typeshed import Incomplete

class GetExtendedCampaignStats:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, global_stats: Incomplete | None = None, campaign_stats: Incomplete | None = None, mirror_click: Incomplete | None = None, remaining: Incomplete | None = None, links_stats: Incomplete | None = None, stats_by_domain: Incomplete | None = None, stats_by_device: Incomplete | None = None, stats_by_browser: Incomplete | None = None) -> None: ...
    @property
    def global_stats(self): ...
    @global_stats.setter
    def global_stats(self, global_stats) -> None: ...
    @property
    def campaign_stats(self): ...
    @campaign_stats.setter
    def campaign_stats(self, campaign_stats) -> None: ...
    @property
    def mirror_click(self): ...
    @mirror_click.setter
    def mirror_click(self, mirror_click) -> None: ...
    @property
    def remaining(self): ...
    @remaining.setter
    def remaining(self, remaining) -> None: ...
    @property
    def links_stats(self): ...
    @links_stats.setter
    def links_stats(self, links_stats) -> None: ...
    @property
    def stats_by_domain(self): ...
    @stats_by_domain.setter
    def stats_by_domain(self, stats_by_domain) -> None: ...
    @property
    def stats_by_device(self): ...
    @stats_by_device.setter
    def stats_by_device(self, stats_by_device) -> None: ...
    @property
    def stats_by_browser(self): ...
    @stats_by_browser.setter
    def stats_by_browser(self, stats_by_browser) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
