from _typeshed import Incomplete

class GetContactCampaignStatsTransacAttributes:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, order_date: Incomplete | None = None, order_price: Incomplete | None = None, order_id: Incomplete | None = None) -> None: ...
    @property
    def order_date(self): ...
    @order_date.setter
    def order_date(self, order_date) -> None: ...
    @property
    def order_price(self): ...
    @order_price.setter
    def order_price(self, order_price) -> None: ...
    @property
    def order_id(self): ...
    @order_id.setter
    def order_id(self, order_id) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
