from _typeshed import Incomplete

class GetSendersListIps:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, ip: Incomplete | None = None, domain: Incomplete | None = None, weight: Incomplete | None = None) -> None: ...
    @property
    def ip(self): ...
    @ip.setter
    def ip(self, ip) -> None: ...
    @property
    def domain(self): ...
    @domain.setter
    def domain(self, domain) -> None: ...
    @property
    def weight(self): ...
    @weight.setter
    def weight(self, weight) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
