from _typeshed import Incomplete

class GetChildInfoApiKeys:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, v2: Incomplete | None = None, v3: Incomplete | None = None) -> None: ...
    @property
    def v2(self): ...
    @v2.setter
    def v2(self, v2) -> None: ...
    @property
    def v3(self): ...
    @v3.setter
    def v3(self, v3) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
