from _typeshed import Incomplete

class GetAccountRelay:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, enabled: Incomplete | None = None, data: Incomplete | None = None) -> None: ...
    @property
    def enabled(self): ...
    @enabled.setter
    def enabled(self, enabled) -> None: ...
    @property
    def data(self): ...
    @data.setter
    def data(self, data) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
