from _typeshed import Incomplete

class GetExtendedCampaignOverview:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, name: Incomplete | None = None, subject: Incomplete | None = None, type: Incomplete | None = None, status: Incomplete | None = None, scheduled_at: Incomplete | None = None, ab_testing: Incomplete | None = None, subject_a: Incomplete | None = None, subject_b: Incomplete | None = None, split_rule: Incomplete | None = None, winner_criteria: Incomplete | None = None, winner_delay: Incomplete | None = None, send_at_best_time: Incomplete | None = None, test_sent: Incomplete | None = None, header: Incomplete | None = None, footer: Incomplete | None = None, sender: Incomplete | None = None, reply_to: Incomplete | None = None, to_field: Incomplete | None = None, html_content: Incomplete | None = None, share_link: Incomplete | None = None, tag: Incomplete | None = None, created_at: Incomplete | None = None, modified_at: Incomplete | None = None, inline_image_activation: Incomplete | None = None, mirror_active: Incomplete | None = None, recurring: Incomplete | None = None, sent_date: Incomplete | None = None, return_bounce: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def subject(self): ...
    @subject.setter
    def subject(self, subject) -> None: ...
    @property
    def type(self): ...
    @type.setter
    def type(self, type) -> None: ...
    @property
    def status(self): ...
    @status.setter
    def status(self, status) -> None: ...
    @property
    def scheduled_at(self): ...
    @scheduled_at.setter
    def scheduled_at(self, scheduled_at) -> None: ...
    @property
    def ab_testing(self): ...
    @ab_testing.setter
    def ab_testing(self, ab_testing) -> None: ...
    @property
    def subject_a(self): ...
    @subject_a.setter
    def subject_a(self, subject_a) -> None: ...
    @property
    def subject_b(self): ...
    @subject_b.setter
    def subject_b(self, subject_b) -> None: ...
    @property
    def split_rule(self): ...
    @split_rule.setter
    def split_rule(self, split_rule) -> None: ...
    @property
    def winner_criteria(self): ...
    @winner_criteria.setter
    def winner_criteria(self, winner_criteria) -> None: ...
    @property
    def winner_delay(self): ...
    @winner_delay.setter
    def winner_delay(self, winner_delay) -> None: ...
    @property
    def send_at_best_time(self): ...
    @send_at_best_time.setter
    def send_at_best_time(self, send_at_best_time) -> None: ...
    @property
    def test_sent(self): ...
    @test_sent.setter
    def test_sent(self, test_sent) -> None: ...
    @property
    def header(self): ...
    @header.setter
    def header(self, header) -> None: ...
    @property
    def footer(self): ...
    @footer.setter
    def footer(self, footer) -> None: ...
    @property
    def sender(self): ...
    @sender.setter
    def sender(self, sender) -> None: ...
    @property
    def reply_to(self): ...
    @reply_to.setter
    def reply_to(self, reply_to) -> None: ...
    @property
    def to_field(self): ...
    @to_field.setter
    def to_field(self, to_field) -> None: ...
    @property
    def html_content(self): ...
    @html_content.setter
    def html_content(self, html_content) -> None: ...
    @property
    def share_link(self): ...
    @share_link.setter
    def share_link(self, share_link) -> None: ...
    @property
    def tag(self): ...
    @tag.setter
    def tag(self, tag) -> None: ...
    @property
    def created_at(self): ...
    @created_at.setter
    def created_at(self, created_at) -> None: ...
    @property
    def modified_at(self): ...
    @modified_at.setter
    def modified_at(self, modified_at) -> None: ...
    @property
    def inline_image_activation(self): ...
    @inline_image_activation.setter
    def inline_image_activation(self, inline_image_activation) -> None: ...
    @property
    def mirror_active(self): ...
    @mirror_active.setter
    def mirror_active(self, mirror_active) -> None: ...
    @property
    def recurring(self): ...
    @recurring.setter
    def recurring(self, recurring) -> None: ...
    @property
    def sent_date(self): ...
    @sent_date.setter
    def sent_date(self, sent_date) -> None: ...
    @property
    def return_bounce(self): ...
    @return_bounce.setter
    def return_bounce(self, return_bounce) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
