from _typeshed import Incomplete

class GetChildInfoStatistics:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, previous_month_total_sent: Incomplete | None = None, current_month_total_sent: Incomplete | None = None, total_sent: Incomplete | None = None) -> None: ...
    @property
    def previous_month_total_sent(self): ...
    @previous_month_total_sent.setter
    def previous_month_total_sent(self, previous_month_total_sent) -> None: ...
    @property
    def current_month_total_sent(self): ...
    @current_month_total_sent.setter
    def current_month_total_sent(self, current_month_total_sent) -> None: ...
    @property
    def total_sent(self): ...
    @total_sent.setter
    def total_sent(self, total_sent) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
