from _typeshed import Incomplete

class GetAggregatedReport:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, range: Incomplete | None = None, requests: Incomplete | None = None, delivered: Incomplete | None = None, hard_bounces: Incomplete | None = None, soft_bounces: Incomplete | None = None, clicks: Incomplete | None = None, unique_clicks: Incomplete | None = None, opens: Incomplete | None = None, unique_opens: Incomplete | None = None, spam_reports: Incomplete | None = None, blocked: Incomplete | None = None, invalid: Incomplete | None = None, unsubscribed: Incomplete | None = None) -> None: ...
    @property
    def range(self): ...
    @range.setter
    def range(self, range) -> None: ...
    @property
    def requests(self): ...
    @requests.setter
    def requests(self, requests) -> None: ...
    @property
    def delivered(self): ...
    @delivered.setter
    def delivered(self, delivered) -> None: ...
    @property
    def hard_bounces(self): ...
    @hard_bounces.setter
    def hard_bounces(self, hard_bounces) -> None: ...
    @property
    def soft_bounces(self): ...
    @soft_bounces.setter
    def soft_bounces(self, soft_bounces) -> None: ...
    @property
    def clicks(self): ...
    @clicks.setter
    def clicks(self, clicks) -> None: ...
    @property
    def unique_clicks(self): ...
    @unique_clicks.setter
    def unique_clicks(self, unique_clicks) -> None: ...
    @property
    def opens(self): ...
    @opens.setter
    def opens(self, opens) -> None: ...
    @property
    def unique_opens(self): ...
    @unique_opens.setter
    def unique_opens(self, unique_opens) -> None: ...
    @property
    def spam_reports(self): ...
    @spam_reports.setter
    def spam_reports(self, spam_reports) -> None: ...
    @property
    def blocked(self): ...
    @blocked.setter
    def blocked(self, blocked) -> None: ...
    @property
    def invalid(self): ...
    @invalid.setter
    def invalid(self, invalid) -> None: ...
    @property
    def unsubscribed(self): ...
    @unsubscribed.setter
    def unsubscribed(self, unsubscribed) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
