from _typeshed import Incomplete

class GetDeviceBrowserStats:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, clickers: Incomplete | None = None, unique_clicks: Incomplete | None = None, viewed: Incomplete | None = None, unique_views: Incomplete | None = None) -> None: ...
    @property
    def clickers(self): ...
    @clickers.setter
    def clickers(self, clickers) -> None: ...
    @property
    def unique_clicks(self): ...
    @unique_clicks.setter
    def unique_clicks(self, unique_clicks) -> None: ...
    @property
    def viewed(self): ...
    @viewed.setter
    def viewed(self, viewed) -> None: ...
    @property
    def unique_views(self): ...
    @unique_views.setter
    def unique_views(self, unique_views) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
