from _typeshed import Incomplete

class GetAttributesAttributes:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, name: Incomplete | None = None, category: Incomplete | None = None, type: Incomplete | None = None, enumeration: Incomplete | None = None, calculated_value: Incomplete | None = None) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def category(self): ...
    @category.setter
    def category(self, category) -> None: ...
    @property
    def type(self): ...
    @type.setter
    def type(self, type) -> None: ...
    @property
    def enumeration(self): ...
    @enumeration.setter
    def enumeration(self, enumeration) -> None: ...
    @property
    def calculated_value(self): ...
    @calculated_value.setter
    def calculated_value(self, calculated_value) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
