from _typeshed import Incomplete

class GetScheduledEmailByBatchId:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, count: Incomplete | None = None, batches: Incomplete | None = None) -> None: ...
    @property
    def count(self): ...
    @count.setter
    def count(self, count) -> None: ...
    @property
    def batches(self): ...
    @batches.setter
    def batches(self, batches) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
