from _typeshed import Incomplete

class GetCampaignRecipients:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, lists: Incomplete | None = None, exclusion_lists: Incomplete | None = None) -> None: ...
    @property
    def lists(self): ...
    @lists.setter
    def lists(self, lists) -> None: ...
    @property
    def exclusion_lists(self): ...
    @exclusion_lists.setter
    def exclusion_lists(self, exclusion_lists) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
