from _typeshed import Incomplete

class GetExternalFeedByUUID:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, name: Incomplete | None = None, url: Incomplete | None = None, auth_type: Incomplete | None = None, username: Incomplete | None = None, password: Incomplete | None = None, token: Incomplete | None = None, headers: Incomplete | None = None, max_retries: Incomplete | None = None, cache: Incomplete | None = None, created_at: Incomplete | None = None, modified_at: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def url(self): ...
    @url.setter
    def url(self, url) -> None: ...
    @property
    def auth_type(self): ...
    @auth_type.setter
    def auth_type(self, auth_type) -> None: ...
    @property
    def username(self): ...
    @username.setter
    def username(self, username) -> None: ...
    @property
    def password(self): ...
    @password.setter
    def password(self, password) -> None: ...
    @property
    def token(self): ...
    @token.setter
    def token(self, token) -> None: ...
    @property
    def headers(self): ...
    @headers.setter
    def headers(self, headers) -> None: ...
    @property
    def max_retries(self): ...
    @max_retries.setter
    def max_retries(self, max_retries) -> None: ...
    @property
    def cache(self): ...
    @cache.setter
    def cache(self, cache) -> None: ...
    @property
    def created_at(self): ...
    @created_at.setter
    def created_at(self, created_at) -> None: ...
    @property
    def modified_at(self): ...
    @modified_at.setter
    def modified_at(self, modified_at) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
