from _typeshed import Incomplete

class GetAccountRelayData:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, user_name: Incomplete | None = None, relay: Incomplete | None = None, port: Incomplete | None = None) -> None: ...
    @property
    def user_name(self): ...
    @user_name.setter
    def user_name(self, user_name) -> None: ...
    @property
    def relay(self): ...
    @relay.setter
    def relay(self, relay) -> None: ...
    @property
    def port(self): ...
    @port.setter
    def port(self, port) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
