from _typeshed import Incomplete

class GetAccountMarketingAutomation:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, key: Incomplete | None = None, enabled: Incomplete | None = None) -> None: ...
    @property
    def key(self): ...
    @key.setter
    def key(self, key) -> None: ...
    @property
    def enabled(self): ...
    @enabled.setter
    def enabled(self, enabled) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
