from _typeshed import Incomplete

class GetCategoryDetails:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, name: Incomplete | None = None, created_at: Incomplete | None = None, modified_at: Incomplete | None = None, url: Incomplete | None = None, is_deleted: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def created_at(self): ...
    @created_at.setter
    def created_at(self, created_at) -> None: ...
    @property
    def modified_at(self): ...
    @modified_at.setter
    def modified_at(self, modified_at) -> None: ...
    @property
    def url(self): ...
    @url.setter
    def url(self, url) -> None: ...
    @property
    def is_deleted(self): ...
    @is_deleted.setter
    def is_deleted(self, is_deleted) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
