from _typeshed import Incomplete

class ManageIp:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, ip: Incomplete | None = None) -> None: ...
    @property
    def ip(self): ...
    @ip.setter
    def ip(self, ip) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
