from _typeshed import Incomplete

class MasterDetailsResponseBillingInfoAddress:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, street_address: Incomplete | None = None, locality: Incomplete | None = None, postal_code: Incomplete | None = None, state_code: Incomplete | None = None, country_code: Incomplete | None = None) -> None: ...
    @property
    def street_address(self): ...
    @street_address.setter
    def street_address(self, street_address) -> None: ...
    @property
    def locality(self): ...
    @locality.setter
    def locality(self, locality) -> None: ...
    @property
    def postal_code(self): ...
    @postal_code.setter
    def postal_code(self, postal_code) -> None: ...
    @property
    def state_code(self): ...
    @state_code.setter
    def state_code(self, state_code) -> None: ...
    @property
    def country_code(self): ...
    @country_code.setter
    def country_code(self, country_code) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
