from _typeshed import Incomplete

class MasterDetailsResponsePlanInfo:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, currency_code: Incomplete | None = None, next_billing_at: Incomplete | None = None, price: Incomplete | None = None, plan_period: Incomplete | None = None, sub_accounts: Incomplete | None = None, features: Incomplete | None = None) -> None: ...
    @property
    def currency_code(self): ...
    @currency_code.setter
    def currency_code(self, currency_code) -> None: ...
    @property
    def next_billing_at(self): ...
    @next_billing_at.setter
    def next_billing_at(self, next_billing_at) -> None: ...
    @property
    def price(self): ...
    @price.setter
    def price(self, price) -> None: ...
    @property
    def plan_period(self): ...
    @plan_period.setter
    def plan_period(self, plan_period) -> None: ...
    @property
    def sub_accounts(self): ...
    @sub_accounts.setter
    def sub_accounts(self, sub_accounts) -> None: ...
    @property
    def features(self): ...
    @features.setter
    def features(self, features) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
