from _typeshed import Incomplete

class MasterDetailsResponseBillingInfoName:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, given_name: Incomplete | None = None, family_name: Incomplete | None = None) -> None: ...
    @property
    def given_name(self): ...
    @given_name.setter
    def given_name(self, given_name) -> None: ...
    @property
    def family_name(self): ...
    @family_name.setter
    def family_name(self, family_name) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
