from _typeshed import Incomplete

class MasterDetailsResponseBillingInfo:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, email: Incomplete | None = None, company_name: Incomplete | None = None, name: Incomplete | None = None, address: Incomplete | None = None) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def company_name(self): ...
    @company_name.setter
    def company_name(self, company_name) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def address(self): ...
    @address.setter
    def address(self, address) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
