from _typeshed import Incomplete

class MasterDetailsResponse:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, email: Incomplete | None = None, company_name: Incomplete | None = None, id: Incomplete | None = None, currency_code: Incomplete | None = None, timezone: Incomplete | None = None, billing_info: Incomplete | None = None, plan_info: Incomplete | None = None) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def company_name(self): ...
    @company_name.setter
    def company_name(self, company_name) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def currency_code(self): ...
    @currency_code.setter
    def currency_code(self, currency_code) -> None: ...
    @property
    def timezone(self): ...
    @timezone.setter
    def timezone(self, timezone) -> None: ...
    @property
    def billing_info(self): ...
    @billing_info.setter
    def billing_info(self, billing_info) -> None: ...
    @property
    def plan_info(self): ...
    @plan_info.setter
    def plan_info(self, plan_info) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
