from _typeshed import Incomplete

class MasterDetailsResponsePlanInfoFeatures:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, name: Incomplete | None = None, unit_value: Incomplete | None = None, quantity: Incomplete | None = None, used: Incomplete | None = None, remaining: Incomplete | None = None) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def unit_value(self): ...
    @unit_value.setter
    def unit_value(self, unit_value) -> None: ...
    @property
    def quantity(self): ...
    @quantity.setter
    def quantity(self, quantity) -> None: ...
    @property
    def used(self): ...
    @used.setter
    def used(self, used) -> None: ...
    @property
    def remaining(self): ...
    @remaining.setter
    def remaining(self, remaining) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
