from _typeshed import Incomplete

class Note:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, text: Incomplete | None = None, contact_ids: Incomplete | None = None, deal_ids: Incomplete | None = None, author_id: Incomplete | None = None, created_at: Incomplete | None = None, updated_at: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, text) -> None: ...
    @property
    def contact_ids(self): ...
    @contact_ids.setter
    def contact_ids(self, contact_ids) -> None: ...
    @property
    def deal_ids(self): ...
    @deal_ids.setter
    def deal_ids(self, deal_ids) -> None: ...
    @property
    def author_id(self): ...
    @author_id.setter
    def author_id(self, author_id) -> None: ...
    @property
    def created_at(self): ...
    @created_at.setter
    def created_at(self, created_at) -> None: ...
    @property
    def updated_at(self): ...
    @updated_at.setter
    def updated_at(self, updated_at) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
