from _typeshed import Incomplete

class NoteData:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, text: Incomplete | None = None, contact_ids: Incomplete | None = None, deal_ids: Incomplete | None = None, company_ids: Incomplete | None = None) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, text) -> None: ...
    @property
    def contact_ids(self): ...
    @contact_ids.setter
    def contact_ids(self, contact_ids) -> None: ...
    @property
    def deal_ids(self): ...
    @deal_ids.setter
    def deal_ids(self, deal_ids) -> None: ...
    @property
    def company_ids(self): ...
    @company_ids.setter
    def company_ids(self, company_ids) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
