from _typeshed import Incomplete

class OrderBilling:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, address: Incomplete | None = None, city: Incomplete | None = None, country_code: Incomplete | None = None, phone: Incomplete | None = None, post_code: Incomplete | None = None, payment_method: Incomplete | None = None, region: Incomplete | None = None) -> None: ...
    @property
    def address(self): ...
    @address.setter
    def address(self, address) -> None: ...
    @property
    def city(self): ...
    @city.setter
    def city(self, city) -> None: ...
    @property
    def country_code(self): ...
    @country_code.setter
    def country_code(self, country_code) -> None: ...
    @property
    def phone(self): ...
    @phone.setter
    def phone(self, phone) -> None: ...
    @property
    def post_code(self): ...
    @post_code.setter
    def post_code(self, post_code) -> None: ...
    @property
    def payment_method(self): ...
    @payment_method.setter
    def payment_method(self, payment_method) -> None: ...
    @property
    def region(self): ...
    @region.setter
    def region(self, region) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
