from _typeshed import Incomplete

class OrderBatch:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, orders: Incomplete | None = None, notify_url: Incomplete | None = None) -> None: ...
    @property
    def orders(self): ...
    @orders.setter
    def orders(self, orders) -> None: ...
    @property
    def notify_url(self): ...
    @notify_url.setter
    def notify_url(self, notify_url) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
