from _typeshed import Incomplete

class Order:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, created_at: Incomplete | None = None, updated_at: Incomplete | None = None, status: Incomplete | None = None, amount: Incomplete | None = None, products: Incomplete | None = None, email: Incomplete | None = None, billing: Incomplete | None = None, coupons: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def created_at(self): ...
    @created_at.setter
    def created_at(self, created_at) -> None: ...
    @property
    def updated_at(self): ...
    @updated_at.setter
    def updated_at(self, updated_at) -> None: ...
    @property
    def status(self): ...
    @status.setter
    def status(self, status) -> None: ...
    @property
    def amount(self): ...
    @amount.setter
    def amount(self, amount) -> None: ...
    @property
    def products(self): ...
    @products.setter
    def products(self, products) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def billing(self): ...
    @billing.setter
    def billing(self, billing) -> None: ...
    @property
    def coupons(self): ...
    @coupons.setter
    def coupons(self, coupons) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
