from _typeshed import Incomplete

class OrderProducts:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, product_id: Incomplete | None = None, quantity: Incomplete | None = None, variant_id: Incomplete | None = None, price: Incomplete | None = None) -> None: ...
    @property
    def product_id(self): ...
    @product_id.setter
    def product_id(self, product_id) -> None: ...
    @property
    def quantity(self): ...
    @quantity.setter
    def quantity(self, quantity) -> None: ...
    @property
    def variant_id(self): ...
    @variant_id.setter
    def variant_id(self, variant_id) -> None: ...
    @property
    def price(self): ...
    @price.setter
    def price(self, price) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
