from _typeshed import Incomplete

class Pipeline:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, stages: Incomplete | None = None) -> None: ...
    @property
    def stages(self): ...
    @stages.setter
    def stages(self, stages) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
