from _typeshed import Incomplete

class PostSendFailed:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, code: Incomplete | None = None, message: Incomplete | None = None, unexisting_emails: Incomplete | None = None, without_list_emails: Incomplete | None = None, black_listed_emails: Incomplete | None = None) -> None: ...
    @property
    def code(self): ...
    @code.setter
    def code(self, code) -> None: ...
    @property
    def message(self): ...
    @message.setter
    def message(self, message) -> None: ...
    @property
    def unexisting_emails(self): ...
    @unexisting_emails.setter
    def unexisting_emails(self, unexisting_emails) -> None: ...
    @property
    def without_list_emails(self): ...
    @without_list_emails.setter
    def without_list_emails(self, without_list_emails) -> None: ...
    @property
    def black_listed_emails(self): ...
    @black_listed_emails.setter
    def black_listed_emails(self, black_listed_emails) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
