from _typeshed import Incomplete

class PostSendSmsTestFailed:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, code: Incomplete | None = None, message: Incomplete | None = None, unexisting_sms: Incomplete | None = None, without_list_sms: Incomplete | None = None) -> None: ...
    @property
    def code(self): ...
    @code.setter
    def code(self, code) -> None: ...
    @property
    def message(self): ...
    @message.setter
    def message(self, message) -> None: ...
    @property
    def unexisting_sms(self): ...
    @unexisting_sms.setter
    def unexisting_sms(self, unexisting_sms) -> None: ...
    @property
    def without_list_sms(self): ...
    @without_list_sms.setter
    def without_list_sms(self, without_list_sms) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
