from _typeshed import Incomplete

class PostContactInfoContacts:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, success: Incomplete | None = None, failure: Incomplete | None = None, total: Incomplete | None = None, process_id: Incomplete | None = None) -> None: ...
    @property
    def success(self): ...
    @success.setter
    def success(self, success) -> None: ...
    @property
    def failure(self): ...
    @failure.setter
    def failure(self, failure) -> None: ...
    @property
    def total(self): ...
    @total.setter
    def total(self, total) -> None: ...
    @property
    def process_id(self): ...
    @process_id.setter
    def process_id(self, process_id) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
