from _typeshed import Incomplete

class RemainingCreditModel:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, child: Incomplete | None = None, reseller: Incomplete | None = None) -> None: ...
    @property
    def child(self): ...
    @child.setter
    def child(self, child) -> None: ...
    @property
    def reseller(self): ...
    @reseller.setter
    def reseller(self, reseller) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
