from _typeshed import Incomplete

class RemoveCredits:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, sms: Incomplete | None = None, email: Incomplete | None = None) -> None: ...
    @property
    def sms(self): ...
    @sms.setter
    def sms(self, sms) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
