from _typeshed import Incomplete

class RequestContactImportNewList:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, list_name: Incomplete | None = None, folder_id: Incomplete | None = None) -> None: ...
    @property
    def list_name(self): ...
    @list_name.setter
    def list_name(self, list_name) -> None: ...
    @property
    def folder_id(self): ...
    @folder_id.setter
    def folder_id(self, folder_id) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
