from _typeshed import Incomplete

class RequestSmsRecipientExport:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, notify_url: Incomplete | None = None, recipients_type: Incomplete | None = None) -> None: ...
    @property
    def notify_url(self): ...
    @notify_url.setter
    def notify_url(self, notify_url) -> None: ...
    @property
    def recipients_type(self): ...
    @recipients_type.setter
    def recipients_type(self, recipients_type) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
