from _typeshed import Incomplete

class RequestContactImport:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, file_url: Incomplete | None = None, file_body: Incomplete | None = None, json_body: Incomplete | None = None, list_ids: Incomplete | None = None, notify_url: Incomplete | None = None, new_list: Incomplete | None = None, email_blacklist: bool = False, sms_blacklist: bool = False, update_existing_contacts: bool = True, empty_contacts_attributes: bool = False) -> None: ...
    @property
    def file_url(self): ...
    @file_url.setter
    def file_url(self, file_url) -> None: ...
    @property
    def file_body(self): ...
    @file_body.setter
    def file_body(self, file_body) -> None: ...
    @property
    def json_body(self): ...
    @json_body.setter
    def json_body(self, json_body) -> None: ...
    @property
    def list_ids(self): ...
    @list_ids.setter
    def list_ids(self, list_ids) -> None: ...
    @property
    def notify_url(self): ...
    @notify_url.setter
    def notify_url(self, notify_url) -> None: ...
    @property
    def new_list(self): ...
    @new_list.setter
    def new_list(self, new_list) -> None: ...
    @property
    def email_blacklist(self): ...
    @email_blacklist.setter
    def email_blacklist(self, email_blacklist) -> None: ...
    @property
    def sms_blacklist(self): ...
    @sms_blacklist.setter
    def sms_blacklist(self, sms_blacklist) -> None: ...
    @property
    def update_existing_contacts(self): ...
    @update_existing_contacts.setter
    def update_existing_contacts(self, update_existing_contacts) -> None: ...
    @property
    def empty_contacts_attributes(self): ...
    @empty_contacts_attributes.setter
    def empty_contacts_attributes(self, empty_contacts_attributes) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
