from _typeshed import Incomplete

class RequestContactExport:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, export_attributes: Incomplete | None = None, custom_contact_filter: Incomplete | None = None, notify_url: Incomplete | None = None) -> None: ...
    @property
    def export_attributes(self): ...
    @export_attributes.setter
    def export_attributes(self, export_attributes) -> None: ...
    @property
    def custom_contact_filter(self): ...
    @custom_contact_filter.setter
    def custom_contact_filter(self, custom_contact_filter) -> None: ...
    @property
    def notify_url(self): ...
    @notify_url.setter
    def notify_url(self, notify_url) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
