from _typeshed import Incomplete

class RequestContactExportCustomContactFilter:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, action_for_contacts: Incomplete | None = None, action_for_email_campaigns: Incomplete | None = None, action_for_sms_campaigns: Incomplete | None = None, list_id: Incomplete | None = None, email_campaign_id: Incomplete | None = None, sms_campaign_id: Incomplete | None = None) -> None: ...
    @property
    def action_for_contacts(self): ...
    @action_for_contacts.setter
    def action_for_contacts(self, action_for_contacts) -> None: ...
    @property
    def action_for_email_campaigns(self): ...
    @action_for_email_campaigns.setter
    def action_for_email_campaigns(self, action_for_email_campaigns) -> None: ...
    @property
    def action_for_sms_campaigns(self): ...
    @action_for_sms_campaigns.setter
    def action_for_sms_campaigns(self, action_for_sms_campaigns) -> None: ...
    @property
    def list_id(self): ...
    @list_id.setter
    def list_id(self, list_id) -> None: ...
    @property
    def email_campaign_id(self): ...
    @email_campaign_id.setter
    def email_campaign_id(self, email_campaign_id) -> None: ...
    @property
    def sms_campaign_id(self): ...
    @sms_campaign_id.setter
    def sms_campaign_id(self, sms_campaign_id) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
