from _typeshed import Incomplete

class SendTransacSms:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, sender: Incomplete | None = None, recipient: Incomplete | None = None, content: Incomplete | None = None, type: str = 'transactional', tag: Incomplete | None = None, web_url: Incomplete | None = None, unicode_enabled: bool = False, organisation_prefix: Incomplete | None = None) -> None: ...
    @property
    def sender(self): ...
    @sender.setter
    def sender(self, sender) -> None: ...
    @property
    def recipient(self): ...
    @recipient.setter
    def recipient(self, recipient) -> None: ...
    @property
    def content(self): ...
    @content.setter
    def content(self, content) -> None: ...
    @property
    def type(self): ...
    @type.setter
    def type(self, type) -> None: ...
    @property
    def tag(self): ...
    @tag.setter
    def tag(self, tag) -> None: ...
    @property
    def web_url(self): ...
    @web_url.setter
    def web_url(self, web_url) -> None: ...
    @property
    def unicode_enabled(self): ...
    @unicode_enabled.setter
    def unicode_enabled(self, unicode_enabled) -> None: ...
    @property
    def organisation_prefix(self): ...
    @organisation_prefix.setter
    def organisation_prefix(self, organisation_prefix) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
