from _typeshed import Incomplete

class SendSms:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, reference: Incomplete | None = None, message_id: Incomplete | None = None, sms_count: Incomplete | None = None, used_credits: Incomplete | None = None, remaining_credits: Incomplete | None = None) -> None: ...
    @property
    def reference(self): ...
    @reference.setter
    def reference(self, reference) -> None: ...
    @property
    def message_id(self): ...
    @message_id.setter
    def message_id(self, message_id) -> None: ...
    @property
    def sms_count(self): ...
    @sms_count.setter
    def sms_count(self, sms_count) -> None: ...
    @property
    def used_credits(self): ...
    @used_credits.setter
    def used_credits(self, used_credits) -> None: ...
    @property
    def remaining_credits(self): ...
    @remaining_credits.setter
    def remaining_credits(self, remaining_credits) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
