from _typeshed import Incomplete

class SendEmail:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, email_to: Incomplete | None = None, email_bcc: Incomplete | None = None, email_cc: Incomplete | None = None, reply_to: Incomplete | None = None, attachment_url: Incomplete | None = None, attachment: Incomplete | None = None, headers: Incomplete | None = None, attributes: Incomplete | None = None, tags: Incomplete | None = None) -> None: ...
    @property
    def email_to(self): ...
    @email_to.setter
    def email_to(self, email_to) -> None: ...
    @property
    def email_bcc(self): ...
    @email_bcc.setter
    def email_bcc(self, email_bcc) -> None: ...
    @property
    def email_cc(self): ...
    @email_cc.setter
    def email_cc(self, email_cc) -> None: ...
    @property
    def reply_to(self): ...
    @reply_to.setter
    def reply_to(self, reply_to) -> None: ...
    @property
    def attachment_url(self): ...
    @attachment_url.setter
    def attachment_url(self, attachment_url) -> None: ...
    @property
    def attachment(self): ...
    @attachment.setter
    def attachment(self, attachment) -> None: ...
    @property
    def headers(self): ...
    @headers.setter
    def headers(self, headers) -> None: ...
    @property
    def attributes(self): ...
    @attributes.setter
    def attributes(self, attributes) -> None: ...
    @property
    def tags(self): ...
    @tags.setter
    def tags(self, tags) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
