from _typeshed import Incomplete

class SendTestEmail:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, email_to: Incomplete | None = None) -> None: ...
    @property
    def email_to(self): ...
    @email_to.setter
    def email_to(self, email_to) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
