from _typeshed import Incomplete

class SendSmtpEmailMessageVersions:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, to: Incomplete | None = None, params: Incomplete | None = None, bcc: Incomplete | None = None, cc: Incomplete | None = None, reply_to: Incomplete | None = None, subject: Incomplete | None = None) -> None: ...
    @property
    def to(self): ...
    @to.setter
    def to(self, to) -> None: ...
    @property
    def params(self): ...
    @params.setter
    def params(self, params) -> None: ...
    @property
    def bcc(self): ...
    @bcc.setter
    def bcc(self, bcc) -> None: ...
    @property
    def cc(self): ...
    @cc.setter
    def cc(self, cc) -> None: ...
    @property
    def reply_to(self): ...
    @reply_to.setter
    def reply_to(self, reply_to) -> None: ...
    @property
    def subject(self): ...
    @subject.setter
    def subject(self, subject) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
