from _typeshed import Incomplete

class SendSmtpEmail:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, sender: Incomplete | None = None, to: Incomplete | None = None, bcc: Incomplete | None = None, cc: Incomplete | None = None, html_content: Incomplete | None = None, text_content: Incomplete | None = None, subject: Incomplete | None = None, reply_to: Incomplete | None = None, attachment: Incomplete | None = None, headers: Incomplete | None = None, template_id: Incomplete | None = None, params: Incomplete | None = None, message_versions: Incomplete | None = None, tags: Incomplete | None = None, scheduled_at: Incomplete | None = None, batch_id: Incomplete | None = None) -> None: ...
    @property
    def sender(self): ...
    @sender.setter
    def sender(self, sender) -> None: ...
    @property
    def to(self): ...
    @to.setter
    def to(self, to) -> None: ...
    @property
    def bcc(self): ...
    @bcc.setter
    def bcc(self, bcc) -> None: ...
    @property
    def cc(self): ...
    @cc.setter
    def cc(self, cc) -> None: ...
    @property
    def html_content(self): ...
    @html_content.setter
    def html_content(self, html_content) -> None: ...
    @property
    def text_content(self): ...
    @text_content.setter
    def text_content(self, text_content) -> None: ...
    @property
    def subject(self): ...
    @subject.setter
    def subject(self, subject) -> None: ...
    @property
    def reply_to(self): ...
    @reply_to.setter
    def reply_to(self, reply_to) -> None: ...
    @property
    def attachment(self): ...
    @attachment.setter
    def attachment(self, attachment) -> None: ...
    @property
    def headers(self): ...
    @headers.setter
    def headers(self, headers) -> None: ...
    @property
    def template_id(self): ...
    @template_id.setter
    def template_id(self, template_id) -> None: ...
    @property
    def params(self): ...
    @params.setter
    def params(self, params) -> None: ...
    @property
    def message_versions(self): ...
    @message_versions.setter
    def message_versions(self, message_versions) -> None: ...
    @property
    def tags(self): ...
    @tags.setter
    def tags(self, tags) -> None: ...
    @property
    def scheduled_at(self): ...
    @scheduled_at.setter
    def scheduled_at(self, scheduled_at) -> None: ...
    @property
    def batch_id(self): ...
    @batch_id.setter
    def batch_id(self, batch_id) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
