from _typeshed import Incomplete

class SendReportEmail:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, to: Incomplete | None = None, body: Incomplete | None = None) -> None: ...
    @property
    def to(self): ...
    @to.setter
    def to(self, to) -> None: ...
    @property
    def body(self): ...
    @body.setter
    def body(self, body) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
