from _typeshed import Incomplete

class SendWhatsappMessage:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, template_id: Incomplete | None = None, text: Incomplete | None = None, sender_number: Incomplete | None = None, contact_numbers: Incomplete | None = None) -> None: ...
    @property
    def template_id(self): ...
    @template_id.setter
    def template_id(self, template_id) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, text) -> None: ...
    @property
    def sender_number(self): ...
    @sender_number.setter
    def sender_number(self, sender_number) -> None: ...
    @property
    def contact_numbers(self): ...
    @contact_numbers.setter
    def contact_numbers(self, contact_numbers) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
