from _typeshed import Incomplete

class SendTestSms:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, phone_number: Incomplete | None = None) -> None: ...
    @property
    def phone_number(self): ...
    @phone_number.setter
    def phone_number(self, phone_number) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
