from _typeshed import Incomplete

class SsoTokenRequest:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, email: Incomplete | None = None, target: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def target(self): ...
    @target.setter
    def target(self, target) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
