from _typeshed import Incomplete

class SubAccountDetailsResponsePlanInfoFeatures:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, inbox: Incomplete | None = None, landing_page: Incomplete | None = None, users: Incomplete | None = None) -> None: ...
    @property
    def inbox(self): ...
    @inbox.setter
    def inbox(self, inbox) -> None: ...
    @property
    def landing_page(self): ...
    @landing_page.setter
    def landing_page(self, landing_page) -> None: ...
    @property
    def users(self): ...
    @users.setter
    def users(self, users) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
