from _typeshed import Incomplete

class SubAccountDetailsResponsePlanInfoCredits:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, sms: Incomplete | None = None, emails: Incomplete | None = None) -> None: ...
    @property
    def sms(self): ...
    @sms.setter
    def sms(self, sms) -> None: ...
    @property
    def emails(self): ...
    @emails.setter
    def emails(self, emails) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
