from _typeshed import Incomplete

class SubAccountDetailsResponsePlanInfoFeaturesLandingPage:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, quantity: Incomplete | None = None, remaining: Incomplete | None = None) -> None: ...
    @property
    def quantity(self): ...
    @quantity.setter
    def quantity(self, quantity) -> None: ...
    @property
    def remaining(self): ...
    @remaining.setter
    def remaining(self, remaining) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
