from _typeshed import Incomplete

class SubAccountDetailsResponse:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, name: Incomplete | None = None, email: Incomplete | None = None, company_name: Incomplete | None = None, plan_info: Incomplete | None = None) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def company_name(self): ...
    @company_name.setter
    def company_name(self, company_name) -> None: ...
    @property
    def plan_info(self): ...
    @plan_info.setter
    def plan_info(self, plan_info) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
