from _typeshed import Incomplete

class SubAccountUpdatePlanRequest:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, credits: Incomplete | None = None, features: Incomplete | None = None) -> None: ...
    @property
    def credits(self): ...
    @credits.setter
    def credits(self, credits) -> None: ...
    @property
    def features(self): ...
    @features.setter
    def features(self, features) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
