from _typeshed import Incomplete

class SubAccountDetailsResponsePlanInfo:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, credits: Incomplete | None = None, features: Incomplete | None = None, plan_type: Incomplete | None = None) -> None: ...
    @property
    def credits(self): ...
    @credits.setter
    def credits(self, credits) -> None: ...
    @property
    def features(self): ...
    @features.setter
    def features(self, features) -> None: ...
    @property
    def plan_type(self): ...
    @plan_type.setter
    def plan_type(self, plan_type) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
