from _typeshed import Incomplete

class SubAccountsResponse:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, count: Incomplete | None = None, sub_accounts: Incomplete | None = None) -> None: ...
    @property
    def count(self): ...
    @count.setter
    def count(self, count) -> None: ...
    @property
    def sub_accounts(self): ...
    @sub_accounts.setter
    def sub_accounts(self, sub_accounts) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
