from _typeshed import Incomplete

class SubAccountsResponseSubAccounts:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, company_name: Incomplete | None = None, active: Incomplete | None = None, created_at: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def company_name(self): ...
    @company_name.setter
    def company_name(self, company_name) -> None: ...
    @property
    def active(self): ...
    @active.setter
    def active(self, active) -> None: ...
    @property
    def created_at(self): ...
    @created_at.setter
    def created_at(self, created_at) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
