from _typeshed import Incomplete

class TaskReminder:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, value: Incomplete | None = None, unit: Incomplete | None = None, types: Incomplete | None = None) -> None: ...
    @property
    def value(self): ...
    @value.setter
    def value(self, value) -> None: ...
    @property
    def unit(self): ...
    @unit.setter
    def unit(self, unit) -> None: ...
    @property
    def types(self): ...
    @types.setter
    def types(self, types) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
