from _typeshed import Incomplete

class TaskList:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, items: Incomplete | None = None) -> None: ...
    @property
    def items(self): ...
    @items.setter
    def items(self, items) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
