from _typeshed import Incomplete

class Task:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, task_type_id: Incomplete | None = None, name: Incomplete | None = None, contacts_ids: Incomplete | None = None, deals_ids: Incomplete | None = None, companies_ids: Incomplete | None = None) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def task_type_id(self): ...
    @task_type_id.setter
    def task_type_id(self, task_type_id) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def contacts_ids(self): ...
    @contacts_ids.setter
    def contacts_ids(self, contacts_ids) -> None: ...
    @property
    def deals_ids(self): ...
    @deals_ids.setter
    def deals_ids(self, deals_ids) -> None: ...
    @property
    def companies_ids(self): ...
    @companies_ids.setter
    def companies_ids(self, companies_ids) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
