from _typeshed import Incomplete

class UpdateChildAccountStatus:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, transactional_email: Incomplete | None = None, transactional_sms: Incomplete | None = None, marketing_automation: Incomplete | None = None, sms_campaign: Incomplete | None = None) -> None: ...
    @property
    def transactional_email(self): ...
    @transactional_email.setter
    def transactional_email(self, transactional_email) -> None: ...
    @property
    def transactional_sms(self): ...
    @transactional_sms.setter
    def transactional_sms(self, transactional_sms) -> None: ...
    @property
    def marketing_automation(self): ...
    @marketing_automation.setter
    def marketing_automation(self, marketing_automation) -> None: ...
    @property
    def sms_campaign(self): ...
    @sms_campaign.setter
    def sms_campaign(self, sms_campaign) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
