from _typeshed import Incomplete

class UpdateBatchContactsContacts:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, email: Incomplete | None = None, id: Incomplete | None = None, sms: Incomplete | None = None, ext_id: Incomplete | None = None, attributes: Incomplete | None = None, email_blacklisted: Incomplete | None = None, sms_blacklisted: Incomplete | None = None, list_ids: Incomplete | None = None, unlink_list_ids: Incomplete | None = None, smtp_blacklist_sender: Incomplete | None = None) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def sms(self): ...
    @sms.setter
    def sms(self, sms) -> None: ...
    @property
    def ext_id(self): ...
    @ext_id.setter
    def ext_id(self, ext_id) -> None: ...
    @property
    def attributes(self): ...
    @attributes.setter
    def attributes(self, attributes) -> None: ...
    @property
    def email_blacklisted(self): ...
    @email_blacklisted.setter
    def email_blacklisted(self, email_blacklisted) -> None: ...
    @property
    def sms_blacklisted(self): ...
    @sms_blacklisted.setter
    def sms_blacklisted(self, sms_blacklisted) -> None: ...
    @property
    def list_ids(self): ...
    @list_ids.setter
    def list_ids(self, list_ids) -> None: ...
    @property
    def unlink_list_ids(self): ...
    @unlink_list_ids.setter
    def unlink_list_ids(self, unlink_list_ids) -> None: ...
    @property
    def smtp_blacklist_sender(self): ...
    @smtp_blacklist_sender.setter
    def smtp_blacklist_sender(self, smtp_blacklist_sender) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
