from _typeshed import Incomplete

class UpdateEmailCampaign:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, tag: Incomplete | None = None, sender: Incomplete | None = None, name: Incomplete | None = None, html_content: Incomplete | None = None, html_url: Incomplete | None = None, scheduled_at: Incomplete | None = None, subject: Incomplete | None = None, reply_to: Incomplete | None = None, to_field: Incomplete | None = None, recipients: Incomplete | None = None, attachment_url: Incomplete | None = None, inline_image_activation: bool = False, mirror_active: Incomplete | None = None, recurring: bool = False, footer: Incomplete | None = None, header: Incomplete | None = None, utm_campaign: Incomplete | None = None, params: Incomplete | None = None, send_at_best_time: Incomplete | None = None, ab_testing: bool = False, subject_a: Incomplete | None = None, subject_b: Incomplete | None = None, split_rule: Incomplete | None = None, winner_criteria: Incomplete | None = None, winner_delay: Incomplete | None = None, ip_warmup_enable: bool = False, initial_quota: Incomplete | None = None, increase_rate: Incomplete | None = None, unsubscription_page_id: Incomplete | None = None, update_form_id: Incomplete | None = None) -> None: ...
    @property
    def tag(self): ...
    @tag.setter
    def tag(self, tag) -> None: ...
    @property
    def sender(self): ...
    @sender.setter
    def sender(self, sender) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def html_content(self): ...
    @html_content.setter
    def html_content(self, html_content) -> None: ...
    @property
    def html_url(self): ...
    @html_url.setter
    def html_url(self, html_url) -> None: ...
    @property
    def scheduled_at(self): ...
    @scheduled_at.setter
    def scheduled_at(self, scheduled_at) -> None: ...
    @property
    def subject(self): ...
    @subject.setter
    def subject(self, subject) -> None: ...
    @property
    def reply_to(self): ...
    @reply_to.setter
    def reply_to(self, reply_to) -> None: ...
    @property
    def to_field(self): ...
    @to_field.setter
    def to_field(self, to_field) -> None: ...
    @property
    def recipients(self): ...
    @recipients.setter
    def recipients(self, recipients) -> None: ...
    @property
    def attachment_url(self): ...
    @attachment_url.setter
    def attachment_url(self, attachment_url) -> None: ...
    @property
    def inline_image_activation(self): ...
    @inline_image_activation.setter
    def inline_image_activation(self, inline_image_activation) -> None: ...
    @property
    def mirror_active(self): ...
    @mirror_active.setter
    def mirror_active(self, mirror_active) -> None: ...
    @property
    def recurring(self): ...
    @recurring.setter
    def recurring(self, recurring) -> None: ...
    @property
    def footer(self): ...
    @footer.setter
    def footer(self, footer) -> None: ...
    @property
    def header(self): ...
    @header.setter
    def header(self, header) -> None: ...
    @property
    def utm_campaign(self): ...
    @utm_campaign.setter
    def utm_campaign(self, utm_campaign) -> None: ...
    @property
    def params(self): ...
    @params.setter
    def params(self, params) -> None: ...
    @property
    def send_at_best_time(self): ...
    @send_at_best_time.setter
    def send_at_best_time(self, send_at_best_time) -> None: ...
    @property
    def ab_testing(self): ...
    @ab_testing.setter
    def ab_testing(self, ab_testing) -> None: ...
    @property
    def subject_a(self): ...
    @subject_a.setter
    def subject_a(self, subject_a) -> None: ...
    @property
    def subject_b(self): ...
    @subject_b.setter
    def subject_b(self, subject_b) -> None: ...
    @property
    def split_rule(self): ...
    @split_rule.setter
    def split_rule(self, split_rule) -> None: ...
    @property
    def winner_criteria(self): ...
    @winner_criteria.setter
    def winner_criteria(self, winner_criteria) -> None: ...
    @property
    def winner_delay(self): ...
    @winner_delay.setter
    def winner_delay(self, winner_delay) -> None: ...
    @property
    def ip_warmup_enable(self): ...
    @ip_warmup_enable.setter
    def ip_warmup_enable(self, ip_warmup_enable) -> None: ...
    @property
    def initial_quota(self): ...
    @initial_quota.setter
    def initial_quota(self, initial_quota) -> None: ...
    @property
    def increase_rate(self): ...
    @increase_rate.setter
    def increase_rate(self, increase_rate) -> None: ...
    @property
    def unsubscription_page_id(self): ...
    @unsubscription_page_id.setter
    def unsubscription_page_id(self, unsubscription_page_id) -> None: ...
    @property
    def update_form_id(self): ...
    @update_form_id.setter
    def update_form_id(self, update_form_id) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
