from _typeshed import Incomplete

class UpdateEmailCampaignRecipients:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, exclusion_list_ids: Incomplete | None = None, list_ids: Incomplete | None = None, segment_ids: Incomplete | None = None) -> None: ...
    @property
    def exclusion_list_ids(self): ...
    @exclusion_list_ids.setter
    def exclusion_list_ids(self, exclusion_list_ids) -> None: ...
    @property
    def list_ids(self): ...
    @list_ids.setter
    def list_ids(self, list_ids) -> None: ...
    @property
    def segment_ids(self): ...
    @segment_ids.setter
    def segment_ids(self, segment_ids) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
