from _typeshed import Incomplete

class UpdateWebhook:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, url: Incomplete | None = None, description: Incomplete | None = None, events: Incomplete | None = None, domain: Incomplete | None = None) -> None: ...
    @property
    def url(self): ...
    @url.setter
    def url(self, url) -> None: ...
    @property
    def description(self): ...
    @description.setter
    def description(self, description) -> None: ...
    @property
    def events(self): ...
    @events.setter
    def events(self, events) -> None: ...
    @property
    def domain(self): ...
    @domain.setter
    def domain(self, domain) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
