from _typeshed import Incomplete

class UpdateSmsCampaign:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, name: Incomplete | None = None, sender: Incomplete | None = None, content: Incomplete | None = None, recipients: Incomplete | None = None, scheduled_at: Incomplete | None = None, unicode_enabled: bool = False, organisation_prefix: Incomplete | None = None, unsubscribe_instruction: Incomplete | None = None) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def sender(self): ...
    @sender.setter
    def sender(self, sender) -> None: ...
    @property
    def content(self): ...
    @content.setter
    def content(self, content) -> None: ...
    @property
    def recipients(self): ...
    @recipients.setter
    def recipients(self, recipients) -> None: ...
    @property
    def scheduled_at(self): ...
    @scheduled_at.setter
    def scheduled_at(self, scheduled_at) -> None: ...
    @property
    def unicode_enabled(self): ...
    @unicode_enabled.setter
    def unicode_enabled(self, unicode_enabled) -> None: ...
    @property
    def organisation_prefix(self): ...
    @organisation_prefix.setter
    def organisation_prefix(self, organisation_prefix) -> None: ...
    @property
    def unsubscribe_instruction(self): ...
    @unsubscribe_instruction.setter
    def unsubscribe_instruction(self, unsubscribe_instruction) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
