from _typeshed import Incomplete

class UpdateBatchContactsModel:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, success_ids: Incomplete | None = None, failure_ids: Incomplete | None = None) -> None: ...
    @property
    def success_ids(self): ...
    @success_ids.setter
    def success_ids(self, success_ids) -> None: ...
    @property
    def failure_ids(self): ...
    @failure_ids.setter
    def failure_ids(self, failure_ids) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
