from _typeshed import Incomplete

class UploadImageModel:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, url: Incomplete | None = None) -> None: ...
    @property
    def url(self): ...
    @url.setter
    def url(self, url) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
