from _typeshed import Incomplete

class WhatsappCampStats:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, sent: Incomplete | None = None, delivered: Incomplete | None = None, read: Incomplete | None = None, unsubscribe: Incomplete | None = None, not_sent: Incomplete | None = None) -> None: ...
    @property
    def sent(self): ...
    @sent.setter
    def sent(self, sent) -> None: ...
    @property
    def delivered(self): ...
    @delivered.setter
    def delivered(self, delivered) -> None: ...
    @property
    def read(self): ...
    @read.setter
    def read(self, read) -> None: ...
    @property
    def unsubscribe(self): ...
    @unsubscribe.setter
    def unsubscribe(self, unsubscribe) -> None: ...
    @property
    def not_sent(self): ...
    @not_sent.setter
    def not_sent(self, not_sent) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
