from _typeshed import Incomplete

class WhatsappCampTemplate:
    swagger_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, name: Incomplete | None = None, category: Incomplete | None = None, language: Incomplete | None = None, contains_button: Incomplete | None = None, display_header: Incomplete | None = None, header_type: Incomplete | None = None, components: Incomplete | None = None, header_variables: Incomplete | None = None, body_variables: Incomplete | None = None, button_type: Incomplete | None = None, hide_footer: Incomplete | None = None) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def category(self): ...
    @category.setter
    def category(self, category) -> None: ...
    @property
    def language(self): ...
    @language.setter
    def language(self, language) -> None: ...
    @property
    def contains_button(self): ...
    @contains_button.setter
    def contains_button(self, contains_button) -> None: ...
    @property
    def display_header(self): ...
    @display_header.setter
    def display_header(self, display_header) -> None: ...
    @property
    def header_type(self): ...
    @header_type.setter
    def header_type(self, header_type) -> None: ...
    @property
    def components(self): ...
    @components.setter
    def components(self, components) -> None: ...
    @property
    def header_variables(self): ...
    @header_variables.setter
    def header_variables(self, header_variables) -> None: ...
    @property
    def body_variables(self): ...
    @body_variables.setter
    def body_variables(self, body_variables) -> None: ...
    @property
    def button_type(self): ...
    @button_type.setter
    def button_type(self, button_type) -> None: ...
    @property
    def hide_footer(self): ...
    @hide_footer.setter
    def hide_footer(self, hide_footer) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
